@php
    $meses = ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];
    $fecha = static function ($valor) use ($meses): string { if (!$valor) return ''; $valor = $valor instanceof \DateTimeInterface ? \Illuminate\Support\Carbon::instance($valor) : \Illuminate\Support\Carbon::parse($valor); return $valor->day.' de '.$meses[$valor->month - 1].' de '.$valor->year; };
    $valor = static function ($dato, string $campo = ''): string { if ($dato === null || $dato === '') return 'Sin información'; if (is_bool($dato)) return $dato ? 'Sí' : 'No'; if (in_array($campo, ['fecha_registro','fecha_inicio','fecha_finalizacion'], true)) { $dato = $dato instanceof \DateTimeInterface ? \Illuminate\Support\Carbon::instance($dato) : \Illuminate\Support\Carbon::parse($dato); return $dato->format('d/m/Y'); } if (is_array($dato)) return collect($dato)->map(fn ($item) => is_array($item) ? implode(' — ', array_filter(array_map('strval', $item))) : (string) $item)->implode('; '); return (string) $dato; };
    $firmas = collect(['coordinador' => $registro->firma_coordinador, 'supervisor' => $registro->firma_supervisor, 'estudiante' => $registro->firma_estudiante])->map(fn ($firma) => \App\Support\Fichas\FirmaImagen::resolver((string) $firma, true));
    $secciones = $secciones ?? [];
@endphp
<!doctype html><html lang="es"><head><meta charset="utf-8"><style>
@page{size:letter portrait;margin:22mm 16mm 20mm}*{box-sizing:border-box}body{color:#172033;font-family:Arial,Helvetica,sans-serif;font-size:8.5pt;line-height:1.25;margin:0}.watermark{bottom:35mm;opacity:.07;position:fixed;right:-65mm;width:180mm;z-index:-1}.header{border-bottom:.6pt solid #001b44;margin-bottom:4mm;padding-bottom:3mm}.header table,.footer table{border-collapse:collapse;width:100%}.brand{width:75%}.brand img{width:100%}.contact{color:#001b44;font-size:7pt;text-align:right;vertical-align:middle;width:25%}.title{text-align:center;color:#001b44;font-weight:bold;font-size:13pt;margin:2mm 0 1mm}.subtitle{text-align:center;color:#001b44;font-size:8pt;margin-bottom:4mm}.section{background:#001b44;color:#fff;font-weight:bold;font-size:9pt;padding:4px 6px;margin-top:5mm;page-break-after:avoid}.data{border-collapse:collapse;width:100%;page-break-inside:auto}.data thead{display:table-header-group}.data tr{page-break-inside:avoid}.data th,.data td{border:.35pt solid #aab4c0;padding:4px;vertical-align:top}.data th{background:#eef2f6;color:#001b44;text-align:left;font-weight:bold;width:38%}.wide{width:62%}.signatures{border-collapse:collapse;margin-top:5mm;page-break-inside:avoid;width:100%}.signatures td{padding:8mm 4mm 2mm;text-align:center;vertical-align:bottom;width:33%}.line{border-top:.6pt solid #172033;margin:0 auto 2mm;width:90%}.attachments{border-collapse:collapse;margin-top:5mm;width:100%;page-break-inside:avoid}.attachments th,.attachments td{border:.35pt solid #aab4c0;padding:4px}.attachments th{background:#eef2f6;color:#001b44;text-align:left}.footer{bottom:-13mm;color:#001b44;font-size:7pt;left:0;position:fixed;right:0;text-align:center}.footer-rule{border-top:.5pt solid #001b44;margin-bottom:2mm}
</style></head><body>
<img class="watermark" src="file://{{ public_path('assets/pdf/common/sol_gris.png') }}" alt=""><div class="header"><table><tr><td class="brand"><img src="file://{{ public_path('assets/pdf/common/vra.png') }}" alt="UNAH, Vicerrectoría Académica y Dirección de Vinculación Universidad-Sociedad"></td><td class="contact">vinculacion.sociedad@unah.edu.hn<br>Tel. 2216-7070 Ext. 110576</td></tr></table></div>
<div class="title">FORM-DVUS-013<br>FORMULARIO DE REGISTRO DE PASANTÍAS</div><div class="subtitle">Universidad Nacional Autónoma de Honduras · Dirección de Vinculación Universidad-Sociedad</div>
@foreach($secciones as $titulo => $campos)<div class="section">{{ $titulo }}</div><table class="data"><thead><tr><th>Ítem</th><th class="wide">Información registrada</th></tr></thead><tbody>@foreach($campos as $etiqueta => $campo)<tr><th>{{ $etiqueta }}</th><td>{{ $valor($registro->{$campo}, $campo) }}</td></tr>@endforeach</tbody></table>@endforeach
<div class="section">VI. FIRMAS</div><table class="signatures"><tr><td>@if($firmas['coordinador']['src'] ?? null)<img src="{{ $firmas['coordinador']['src'] }}" style="height:14mm;max-width:55mm" alt="">@else<div class="line"></div>@endif<strong>Coordinador de la carrera</strong><br>{{ $valor($registro->nombre_firma_coordinador) }}</td><td>@if($firmas['supervisor']['src'] ?? null)<img src="{{ $firmas['supervisor']['src'] }}" style="height:14mm;max-width:55mm" alt="">@else<div class="line"></div>@endif<strong>Supervisor de la pasantía</strong><br>{{ $valor($registro->nombre_firma_supervisor) }}</td><td>@if($firmas['estudiante']['src'] ?? null)<img src="{{ $firmas['estudiante']['src'] }}" style="height:14mm;max-width:55mm" alt="">@else<div class="line"></div>@endif<strong>Estudiante que realiza la pasantía</strong><br>{{ $valor($registro->nombre_firma_estudiante) }}</td></tr></table>
<div class="section">VII. DOCUMENTOS ADJUNTOS A LA FICHA</div><table class="attachments"><thead><tr><th>No.</th><th>Descripción</th><th>Estado</th><th>Archivo</th></tr></thead><tbody><tr><td>1</td><td>Carta formal de solicitud a la unidad académica</td><td>{{ $valor($registro->adjunta_carta_formalizacion) }}</td><td>{{ $valor($registro->archivo_carta_formalizacion) }}</td></tr><tr><td>2</td><td>Convenio marco entre la UNAH y entidad (en el caso de tenerse)</td><td>{{ $valor($registro->adjunta_convenio_marco) }}</td><td>{{ $valor($registro->archivo_convenio_marco) }}</td></tr></tbody></table>
<div class="footer"><div class="footer-rule"></div>Universidad Nacional Autónoma de Honduras · Dirección de Vinculación Universidad-Sociedad<br>“La Educación es la Primera Necesidad de la República”</div></body></html>
