<?php

namespace App\Livewire\Configuracion;

use App\Models\IntegracionApi;
use App\Services\Integraciones\IntegracionApiService;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Gate;
use Illuminate\Validation\Rule;
use Livewire\Component;

class IntegracionesApi extends Component
{
    public ?int $editingId=null; public bool $showForm=false; public string $testValue=''; public array $testResult=[];
    public array $form=[];
    public function mount(): void { $this->authorizeAdmin(); $this->resetForm(); }
    public function authorizeAdmin(): void { abort_unless(auth()->user()?->can('configuracion.integraciones-api'),403); }
    public function resetForm(): void { $this->editingId=null; $this->form=['nombre'=>'','codigo'=>'','tipo_perfil'=>'ESTUDIANTE','base_url'=>'','ruta_busqueda'=>'','metodo_http'=>'GET','tipo_autenticacion'=>'NINGUNA','token'=>'','usuario_api'=>'','password_api'=>'','api_key_header'=>'','parametro_busqueda'=>'numero_cuenta','timeout_segundos'=>15,'headers_json'=>'{}','ruta_respuesta'=>'','mapeo_campos_json'=>json_encode(['numero_cuenta'=>'numeroCuenta','nombres'=>'nombres','apellidos'=>'apellidos','sexo'=>'sexo','correo'=>'correo','carrera'=>'carrera'],JSON_PRETTY_PRINT),'activo'=>false,'eliminar_credencial'=>false]; }
    public function create(): void { $this->authorizeAdmin(); $this->resetForm(); $this->showForm=true; }
    public function edit(int $id): void { $this->authorizeAdmin(); $api=IntegracionApi::findOrFail($id); $this->resetForm(); $this->editingId=$api->id; foreach (['nombre','codigo','tipo_perfil','base_url','ruta_busqueda','metodo_http','tipo_autenticacion','api_key_header','parametro_busqueda','timeout_segundos','ruta_respuesta','activo'] as $field) $this->form[$field]=$api->{$field}; $this->form['headers_json']=json_encode($api->headers_json ?? [],JSON_PRETTY_PRINT); $this->form['mapeo_campos_json']=json_encode($api->mapeo_campos_json ?? [],JSON_PRETTY_PRINT); $this->showForm=true; }
    public function save(): void { $this->authorizeAdmin(); $data=$this->validated(); $api=$this->editingId ? IntegracionApi::findOrFail($this->editingId) : new IntegracionApi(['created_by'=>auth()->id()]); $credentials=['token_encriptado'=>'token','usuario_api_encriptado'=>'usuario_api','password_api_encriptado'=>'password_api']; foreach ($credentials as $column=>$field) if (filled($this->form[$field])) $data[$column]=$this->form[$field]; if ($this->form['eliminar_credencial']) foreach (array_keys($credentials) as $column) $data[$column]=null; $data['headers_json']=json_decode($this->form['headers_json'],true); $data['mapeo_campos_json']=json_decode($this->form['mapeo_campos_json'],true); $data['updated_by']=auth()->id(); if ($data['activo'] && ! $this->complete($data,$api)) { $this->addError('form.activo','La integración activa requiere configuración completa.'); return; } $api->fill($data)->save(); $this->showForm=false; $this->dispatch('integracion-guardada'); }
    public function toggle(int $id): void { $this->authorizeAdmin(); $api=IntegracionApi::findOrFail($id); if (! $api->activo && ! $this->complete($api->toArray(),$api)) { $this->addError('toggle','La integración requiere configuración completa.'); return; } $api->update(['activo'=>!$api->activo,'updated_by'=>auth()->id()]); }
    public function test(int $id, IntegracionApiService $service): void { $this->authorizeAdmin(); $this->validate(['testValue'=>['required','regex:/^\d+$/']]); $this->testResult=$service->probarConexion(IntegracionApi::findOrFail($id),$this->testValue); }
    private function validated(): array { $rules=['form.nombre'=>['required','string','max:255'],'form.codigo'=>['required','alpha_dash','max:100',Rule::unique('integraciones_api','codigo')->ignore($this->editingId)],'form.tipo_perfil'=>[Rule::in(['ESTUDIANTE','PERSONA','EMPLEADO','EXTERNO'])],'form.base_url'=>['required','url'],'form.ruta_busqueda'=>['nullable','string','max:255'],'form.metodo_http'=>[Rule::in(['GET','POST'])],'form.tipo_autenticacion'=>[Rule::in(['NINGUNA','BEARER','API_KEY','BASIC'])],'form.parametro_busqueda'=>['required','string','max:100'],'form.timeout_segundos'=>['required','integer','between:1,120'],'form.headers_json'=>['required','json'],'form.mapeo_campos_json'=>['required','json'],'form.activo'=>['boolean']]; if ($this->form['tipo_autenticacion']==='BEARER' && ! $this->editingId) $rules['form.token']=['required']; if ($this->form['tipo_autenticacion']==='API_KEY') { $rules['form.api_key_header']=['required','string']; if (! $this->editingId) $rules['form.token']=['required']; } if ($this->form['tipo_autenticacion']==='BASIC' && ! $this->editingId) { $rules['form.usuario_api']=['required']; $rules['form.password_api']=['required']; } $this->validate($rules); $headers=json_decode($this->form['headers_json'],true); $mapping=json_decode($this->form['mapeo_campos_json'],true); if (! is_array($headers) || collect($headers)->filter(fn($v,$k)=>!is_string($k)||is_array($v)||is_object($v))->isNotEmpty()) $this->addError('form.headers_json','Los headers deben ser un objeto JSON con valores simples.'); if (! is_array($mapping) || collect($mapping)->keys()->diff(IntegracionApiService::ESTUDIANTE_FIELDS)->isNotEmpty()) $this->addError('form.mapeo_campos_json','El mapeo contiene campos internos no permitidos.'); if ($this->getErrorBag()->isNotEmpty()) $this->validate(); return collect($this->form)->only(['nombre','codigo','tipo_perfil','base_url','ruta_busqueda','metodo_http','tipo_autenticacion','api_key_header','parametro_busqueda','timeout_segundos','ruta_respuesta','activo'])->all(); }
    private function complete(array $data, IntegracionApi $api): bool { return filled($data['base_url'] ?? null) && filled($data['parametro_busqueda'] ?? null) && filled($data['mapeo_campos_json'] ?? null) && (($data['tipo_autenticacion'] ?? 'NINGUNA')==='NINGUNA' || filled($api->token_encriptado) || filled($data['token_encriptado'] ?? null)); }
    public function render(): View { $this->authorizeAdmin(); return view('livewire.configuracion.integraciones-api',['integraciones'=>IntegracionApi::latest()->get()]); }
}
