<?php

return [
    [
        'titulo' => 'Dashboard',
        'icono' => 'ri-dashboard-line',
        'items' => [
            [
                'titulo' => 'Inicio',
                'route' => 'inicio',
                'routes' => ['inicio'],
                'permisos' => ['inicio.admin', 'dashboard.admin', 'dashboard.docente', 'dashboard.estudiante'],
                'icono' => 'heroicon-o-home',
                'children' => [],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Demografía',
                'route' => 'listarPaises',
                'routes' => [
                    'listarPaises',
                    'crearPais',
                    'listarDepartamentos',
                    'crearDepartamento',
                    'ListarMunicipios',
                    'crearMunicipio',
                    'ListarAldeas',
                    'crearAldea',
                    'ListarCiudades',
                    'crearCiudad',
                ],
                'permisos' => [
                    'demografia.pais',
                    'demografia.departamento',
                    'demografia.municipio',
                    'demografia.aldea',
                    'demografia.ciudad',
                ],
                'icono' => 'heroicon-o-map-pin',
                'children' => [
                    ['texto' => 'Pais', 'route' => 'listarPaises', 'permiso' => 'demografia.pais'],
                    ['texto' => 'Departamento', 'route' => 'listarDepartamentos', 'permiso' => 'demografia.departamento'],
                    ['texto' => 'Municipios', 'route' => 'ListarMunicipios', 'permiso' => 'demografia.municipio'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Usuarios',
                'route' => 'Usuarios',
                'routes' => ['Usuarios', 'roles', 'listPermisos'],
                'icono' => 'heroicon-o-user-group',
                'permisos' => ['usuarios.usuarios', 'usuarios.roles', 'usuarios.permisos'],
                'children' => [
                    ['texto' => 'Usuarios', 'route' => 'Usuarios', 'permiso' => 'usuarios.usuarios'],
                    ['texto' => 'Roles', 'route' => 'roles', 'permiso' => 'usuarios.roles'],
                    ['texto' => 'Permisos', 'route' => 'listPermisos', 'permiso' => 'usuarios.permisos'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Constancias',
                'route' => 'constancias',
                'routes' => ['constancias'],
                'icono' => 'heroicon-o-document-text',
                'permisos' => ['constancia.constancias'],
                'children' => [
                    ['texto' => 'Constancias', 'route' => 'constancias', 'permiso' => 'constancia.constancias'],
                    //['texto' => 'Solicitudes', 'route' => 'crearEmpleado', 'permiso' => 'empleados.empleados'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Empleado',
                'route' => 'ListarEmpleados',
                'routes' => ['ListarEmpleados', 'crearEmpleado'],
                'icono' => 'heroicon-c-cube',
                'permisos' => ['empleados.empleados'],
                'children' => [
                    ['texto' => 'Empleados', 'route' => 'ListarEmpleados', 'permiso' => 'empleados.empleados'],
                    ['texto' => 'Crear Empleado', 'route' => 'crearEmpleado', 'permiso' => 'empleados.empleados'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Estudiantes',
                'route' => 'listarEstudiante',
                'routes' => ['listarEstudiante', 'crearEstudiante'],
                'permisos' => ['dashboard.admin'],
                'icono' => 'heroicon-c-book-open',
                'children' => [
                    ['texto' => 'Estudiantes', 'route' => 'listarEstudiante', 'permiso' => 'estudiante.admin'],
                    ['texto' => 'Crear Estudiante', 'route' => 'crearEstudiante', 'permiso' => 'estudiante.admin'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Vinculación',
                'route' => 'listarProyectosVinculacion',
                'routes' => [
                    'listarProyectosVinculacion',
                    'listarProyectosSolicitado',
                    'listarProyectoRevisionFinal',
                    'listarInformesSolicitado',
                    'proyectos.revision-final',
                    'proyectos.informes',
                    'proyectos.historial',
                    'fichasActualizacionVinculacion',
                    'codigosInvestigacionAdmin',
                ],
                'icono' => 'heroicon-m-puzzle-piece',
                'permisos' => [
                    'proyectos.historial',
                    'proyectos.solicitados',
                    'proyectos.aprobados',
                    'proyectos.informes',
                    'proyectos.revision-final',
                ],
                'children' => [
                    ['texto' => 'Historial Vinculación', 'route' => 'listarProyectosVinculacion', 'permiso' => 'proyectos.historial'],
                    ['texto' => 'Revisión DVUS', 'route' => 'listarProyectosSolicitado', 'permiso' => 'proyectos.solicitados', 'funcion' => 'obtenerCantidadProyectosEnRevision'],
                    ['texto' => 'Revisión de Informes', 'route' => 'listarInformesSolicitado', 'permiso' => 'proyectos.informes', 'funcion' => 'obtenerCantidadInformesSolicitados'],
                    ['texto' => 'Firma Director DVUS', 'route' => 'listarProyectoRevisionFinal', 'permiso' => 'proyectos.revision-final', 'funcion' => 'obtenerCantidadProyectosEnRevisionFinal'],
                    ['texto' => 'Fichas de Actualización', 'route' => 'fichasActualizacionVinculacion', 'permiso' => 'proyectos.revision-final'],
                    ['texto' => 'Validar Códigos de Proyectos', 'route' => 'codigosInvestigacionAdmin', 'permiso' => 'proyectos.revision-final'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Unidad Academica',
                'route' => 'campus',
                'routes' => ['campus', 'carrera', 'departamento-academico', 'facultad-centro'],
                'icono' => 'heroicon-o-academic-cap',
                'permisos' => [
                    'unidad-academica.campus',
                    'unidad-academica.carrera',
                    'unidad-academica.departamento',
                    'unidad-academica.facultad',
                ],
                'children' => [
                    ['texto' => 'Campus', 'route' => 'campus', 'permiso' => 'unidad-academica.campus'],
                    ['texto' => 'Carrera', 'route' => 'carrera', 'permiso' => 'unidad-academica.carrera'],
                    ['texto' => 'Departamento Academico', 'route' => 'departamento-academico', 'permiso' => 'unidad-academica.departamento'],
                    ['texto' => 'Facultad Centro', 'route' => 'facultad-centro', 'permiso' => 'unidad-academica.facultad'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],

            [
                'titulo' => 'Configuración',
                'route' => 'listarLogs',
                'routes' => ['listarLogs', 'slides', 'configuracion.flujos.proyectos'],
                'icono' => 'heroicon-c-cog-6-tooth',
                'class' => 'mb-4',
                'permisos' => ['configuracion.logs', 'apariencia.slides', 'configuracion.flujos'],
                'children' => [
                    ['texto' => 'Logs', 'route' => 'listarLogs', 'permiso' => 'configuracion.logs'],
                    ['texto' => 'Apariencia', 'route' => 'slides', 'permiso' => 'apariencia.slides'],
                    ['texto' => 'Flujos de proyectos', 'route' => 'configuracion.flujos.proyectos', 'permiso' => 'configuracion.flujos'],
                    ['texto' => 'Contactanos', 'route' => 'contactanos', 'permiso' => 'configuracion.contactanos']
                ],
            ],
            [
                'titulo' => 'SGCU',
                'route' => 'sgcu.catalogos',
                'routes' => [
                    'sgcu.catalogos',
                    'sgcu.tipos-programa',
                    'sgcu.programas',
                    'sgcu.bandeja-revision',
                    'sgcu.flujos-programa',
                ],
                'icono' => 'heroicon-c-clipboard-document-list',
                'permisos' => ['configuracion.flujos'],
                'children' => [
                    ['texto' => 'Catalogos', 'route' => 'sgcu.catalogos', 'permiso' => 'configuracion.flujos'],
                    ['texto' => 'Tipos de programa', 'route' => 'sgcu.tipos-programa', 'permiso' => 'configuracion.flujos'],
                    ['texto' => 'Programas', 'route' => 'sgcu.programas', 'permiso' => 'configuracion.flujos'],
                    ['texto' => 'Bandeja revision', 'route' => 'sgcu.bandeja-revision', 'permiso' => 'configuracion.flujos'],
                    ['texto' => 'Flujos de programa', 'route' => 'sgcu.flujos-programa', 'permiso' => 'configuracion.flujos'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],

            // director enlace de vinculacion
            [
                'titulo' => 'Historial Vinculación',
                'route' => 'proyectosCentroFacultad',
                'routes' => ['proyectosCentroFacultad'],
                'icono' => 'heroicon-o-academic-cap',
                'permisos' => ['director.proyectos'],
                'children' => [],
                'funcion' => null,
                'can' => 'director.proyectos',
            ],
            // modulo docentes
            [
                'titulo' => 'Vinculación',
                'route' => 'proyectosDocente',
                'routes' => ['proyectosDocente', 'crearProyectoVinculacion'],
                'icono' => 'heroicon-o-academic-cap',
                'permisos' => ['docente.proyectos'],
                'children' => [
                    ['texto' => 'Registrar Acción', 'route' => 'selectorTipoAccion', 'permiso' => 'docente.proyectos'],
                    ['texto' => 'Mi Historial Vinculación', 'route' => 'proyectosDocente', 'permiso' => 'docente.proyectos'],
                    ['texto' => 'Mis Fichas de Actualización', 'route' => 'FichasActualizacionDocente', 'permiso' => 'docente.proyectos'],
                    ['texto' => 'Vinculaciones Antes del Sistema', 'route' => 'proyectosAntesDelSistema', 'permiso' => 'docente.proyectos'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Trazabilidad de Registros',
                'route' => 'SolicitudProyectosDocente',
                'routes' => ['SolicitudProyectosDocente', 'AprobadoProyectosDocente', 'RechazadoProyectosDocente', 'FichasActualizacionPorFirmar'],
                'icono' => 'heroicon-o-document-text',
                'permisos' => ['docente.proyectos'],
                'children' => [
                    ['texto' => 'Revisión Comité Local', 'route' => 'SolicitudProyectosDocente', 'permiso' => 'docente.proyectos', 'funcion' => 'obtenerCantidadProyectosPorFirmar'],
                    ['texto' => 'Fichas de Actualización', 'route' => 'FichasActualizacionPorFirmar', 'permiso' => 'docente.proyectos', 'funcion' => 'obtenerCantidadFichasPorFirmar'],
                    ['texto' => 'Firmas Aprobadas', 'route' => 'AprobadoProyectosDocente', 'permiso' => 'docente.proyectos'],
                    ['texto' => 'Firmas Proximas', 'route' => 'RechazadoProyectosDocente', 'permiso' => 'docente.proyectos'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
             [
                'titulo' => 'Ticket',
                'route' => 'listarTicket',
                'routes' => ['listarTicket'],
                'permisos' => ['dashboard.admin', 'dashboard.docente','dashboard.director', 'dashboard.estudiante', 'tickets.ver'],
                'icono' => 'heroicon-o-ticket',
                'children' => [
                    ['texto' => 'Tickets', 'route' => 'listarTicket', 'permiso' => 'tickets.ver'],
                     ['texto' => 'Historial de Tickets', 'route' => 'historialTicket', 'permiso' => 'tickets.ver'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            
        ],
    ],
];
