<?php

return [
    [
        'titulo' => 'Dashboard',
        'icono' => 'ri-dashboard-line',
        'items' => [
            [
                'titulo' => 'Inicio',
                'route' => 'inicio',
                'routes' => ['inicio'],
                'permisos' => ['inicio-admin-inicio', 'ver-dashboard-admin', 'ver-dashboard-docente'],
                'icono' => 'heroicon-o-home',
                'children' => [],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Demografía',
                'route' => 'listarPaises',
                'routes' => [
                    'listarPaises',
                    'crearPais',
                    'listarDepartamentos',
                    'crearDepartamento',
                    'ListarMunicipios',
                    'crearMunicipio',
                    'ListarAldeas',
                    'crearAldea',
                    'ListarCiudades',
                    'crearCiudad',
                ],
                'permisos' => [
                    'demografia-admin-pais',
                    'demografia-admin-departamento',
                    'demografia-admin-municipio',
                    'demografia-admin-aldea',
                    'demografia-admin-ciudad',
                ],
                'icono' => 'heroicon-o-map-pin',
                'children' => [
                    ['texto' => 'Pais', 'route' => 'listarPaises', 'permiso' => 'demografia-admin-pais'],
                    ['texto' => 'Departamento', 'route' => 'listarDepartamentos', 'permiso' => 'demografia-admin-departamento'],
                    ['texto' => 'Municipios', 'route' => 'ListarMunicipios', 'permiso' => 'demografia-admin-municipio'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Usuarios',
                'route' => 'Usuarios',
                'routes' => ['Usuarios', 'roles', 'listPermisos'],
                'icono' => 'heroicon-o-user-group',
                'permisos' => ['usuarios-admin-usuarios', 'usuarios-admin-rol', 'usuarios-admin-permiso'],
                'children' => [
                    ['texto' => 'Usuarios', 'route' => 'Usuarios', 'permiso' => 'usuarios-admin-usuarios'],
                    ['texto' => 'Roles', 'route' => 'roles', 'permiso' => 'usuarios-admin-rol'],
                    ['texto' => 'Permisos', 'route' => 'listPermisos', 'permiso' => 'usuarios-admin-permiso'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Constancias',
                'route' => 'constancias',
                'routes' => ['constancias'],
                'icono' => 'heroicon-o-document-text',
                'permisos' => ['constancia-admin-constancias'],
                'children' => [],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Empleado',
                'route' => 'ListarEmpleados',
                'routes' => ['ListarEmpleados', 'crearEmpleado'],
                'icono' => 'heroicon-c-cube',
                'permisos' => ['empleados-admin-empleados'],
                'children' => [
                    ['texto' => 'Empleados', 'route' => 'ListarEmpleados', 'permiso' => 'empleados-admin-empleados'],
                    ['texto' => 'Crear Empleado', 'route' => 'crearEmpleado', 'permiso' => 'empleados-admin-empleados'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Proyecto',
                'route' => 'listarProyectosVinculacion',
                'routes' => [
                    'listarProyectosVinculacion',
                    'listarProyectosSolicitado',
                    'listarProyectoRevisionFinal',
                    'listarInformesSolicitado',
                    'proyectos-admin-revision-final',
                    'proyectos-admin-informenes',
                    'proyectos-admin-proyectos',
                ],
                'icono' => 'heroicon-m-puzzle-piece',
                'permisos' => [
                    'proyectos-admin-proyectos',
                    'proyectos-admin-solicitados',
                    'proyectos-admin-aprobados',
                    'proyectos-admin-informenes',
                    'proyectos-admin-revision-final',
                ],
                'children' => [
                    ['texto' => 'Proyectos', 'route' => 'listarProyectosVinculacion', 'permiso' => 'proyectos-admin-proyectos'],
                    ['texto' => 'Solicitud Proyecto', 'route' => 'listarProyectosSolicitado', 'permiso' => 'proyectos-admin-solicitados', 'funcion' => 'obtenerCantidadProyectosEnRevision'],
                    ['texto' => 'Revisión de Informes', 'route' => 'listarInformesSolicitado', 'permiso' => 'proyectos-admin-informenes', 'funcion' => 'obtenerCantidadInformesSolicitados'],
                    ['texto' => 'Revisión Final', 'route' => 'listarProyectoRevisionFinal', 'permiso' => 'proyectos-admin-revision-final', 'funcion' => 'obtenerCantidadProyectosEnRevisionFinal'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Unidad Academica',
                'route' => 'campus',
                'routes' => ['campus', 'carrera', 'departamento-academico', 'facultad-centro'],
                'icono' => 'heroicon-o-academic-cap',
                'permisos' => [
                    'unidad-academica-admin-campus',
                    'unidad-academica-admin-carrera',
                    'unidad-academica-admin-departamento',
                    'unidad-academica-admin-facultad',
                ],
                'children' => [
                    ['texto' => 'Campus', 'route' => 'campus', 'permiso' => 'unidad-academica-admin-campus'],
                    ['texto' => 'Carrera', 'route' => 'carrera', 'permiso' => 'unidad-academica-admin-carrera'],
                    ['texto' => 'Departamento Academico', 'route' => 'departamento-academico', 'permiso' => 'unidad-academica-admin-departamento'],
                    ['texto' => 'Facultad Centro', 'route' => 'facultad-centro', 'permiso' => 'unidad-academica-admin-facultad'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],

            [
                'titulo' => 'Configuración',
                'route' => 'listarLogs',
                'routes' => ['listarLogs', 'slides'],
                'icono' => 'heroicon-c-cog-6-tooth',
                'class' => 'mb-4',
                'permisos' => ['configuracion-admin-logs', 'apariencia-admin-slides'],
                'children' => [
                    ['texto' => 'Logs', 'route' => 'listarLogs', 'permiso' => 'configuracion-admin-logs'],
                    ['texto' => 'Apariencia', 'route' => 'slides', 'permiso' => 'apariencia-admin-slides'],
                    ['texto' => 'Contactanos', 'route' => 'contactanos', 'permiso' => 'configuracion-admin-contactanos']
                ],
            ],

            // director enlace de vinculacion
            [
                'titulo' => 'Proyectos',
                'route' => 'proyectosCentroFacultad',
                'routes' => ['proyectosCentroFacultad'],
                'icono' => 'heroicon-o-academic-cap',
                'permisos' => ['admin_centro_facultad-proyectos'],
                'children' => [],
                'funcion' => null,
                'can' => 'admin_centro_facultad-proyectos',
            ],
            // modulo docentes
            [
                'titulo' => 'Proyectos',
                'route' => 'proyectosDocente',
                'routes' => ['proyectosDocente', 'crearProyectoVinculacion'],
                'icono' => 'heroicon-o-academic-cap',
                'permisos' => ['docente-admin-proyectos'],
                'children' => [
                    ['texto' => 'Proyectos', 'route' => 'proyectosDocente', 'permiso' => 'docente-admin-proyectos'],
                    ['texto' => 'Crear Proyecto', 'route' => 'crearProyectoVinculacion', 'permiso' => 'docente-admin-proyectos'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],
            [
                'titulo' => 'Firmas',
                'route' => 'SolicitudProyectosDocente',
                'routes' => ['SolicitudProyectosDocente', 'AprobadoProyectosDocente', 'RechazadoProyectosDocente'],
                'icono' => 'heroicon-o-document-text',
                'permisos' => ['docente-admin-proyectos', 'docente-admin-solicitados'],
                'children' => [
                    ['texto' => 'Solicitud de Firma', 'route' => 'SolicitudProyectosDocente', 'permiso' => 'docente-admin-proyectos', 'funcion' => 'obtenerCantidadProyectosPorFirmar'],
                    ['texto' => 'Firmas Aprobadas', 'route' => 'AprobadoProyectosDocente', 'permiso' => 'docente-admin-proyectos'],
                    ['texto' => 'Firmas Proximas', 'route' => 'RechazadoProyectosDocente', 'permiso' => 'docente-admin-proyectos'],
                ],
                'funcion' => null,
                'parametro' => null,
                'can' => null,
            ],

            
            
        ],
    ],
];
