@php
    $steps = [1=>'Información',2=>'Beneficiarios',3=>'Equipo',4=>'Contrapartes',5=>'Resultados',6=>'Reflexión y ODS',7=>'Valoración y presupuesto',8=>'Anexos y cierre'];
    $input = 'mt-1 block w-full rounded-md border-gray-300 bg-white text-sm text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-100';
    $readonly = $input.' bg-gray-50 dark:bg-gray-700';
    $label = 'block text-sm font-medium text-gray-700 dark:text-gray-300';
    $button = 'inline-flex items-center justify-center rounded-md px-4 py-2 text-sm font-medium transition focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500';
@endphp

<div class="mx-auto max-w-7xl space-y-4 px-4 py-6 text-gray-900 dark:text-gray-100 sm:px-6">
    <header class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-900">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
            <div>
                <p class="text-xs font-semibold uppercase tracking-wide text-blue-700 dark:text-blue-300">INF-001</p>
                <h1 class="mt-1 text-xl font-bold">Informe Final de Programas y Proyectos de Vinculación</h1>
                <p class="mt-1 text-sm text-gray-600 dark:text-gray-400">{{ $general['nombre_proyecto'] ?: 'Proyecto sin nombre' }} · {{ $general['numero_registro'] }}</p>
            </div>
            <span class="self-start rounded-full px-3 py-1 text-xs font-semibold {{ ($general['estado'] ?? '') === 'COMPLETO' ? 'bg-green-100 text-green-800 dark:bg-green-900/40 dark:text-green-200' : 'bg-amber-100 text-amber-800 dark:bg-amber-900/40 dark:text-amber-200' }}">{{ $general['estado'] ?? 'BORRADOR' }}</span>
        </div>
        @if($mensaje)<div class="mt-4 rounded-md border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800 dark:border-green-900 dark:bg-green-950/30 dark:text-green-200">{{ $mensaje }}</div>@endif
        @if($errors->any())<div class="mt-4 rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800 dark:border-red-900 dark:bg-red-950/30 dark:text-red-200"><p class="font-semibold">Revise los datos señalados.</p><ul class="mt-1 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    </header>

    <nav aria-label="Pasos del informe final" class="rounded-lg border border-gray-200 bg-white p-4 shadow-sm dark:border-gray-700 dark:bg-gray-900">
        <div class="md:hidden">
            <p class="text-sm font-semibold">Paso {{ $currentStep }} de 8</p>
            <p class="text-sm text-gray-600 dark:text-gray-400">{{ $steps[$currentStep] }}</p>
            <div class="mt-2 h-2 overflow-hidden rounded-full bg-gray-200 dark:bg-gray-700"><div class="h-full bg-blue-600" style="width: {{ $currentStep / 8 * 100 }}%"></div></div>
        </div>
        <div class="hidden gap-2 md:grid md:grid-cols-4 lg:grid-cols-8">
            @foreach($steps as $step=>$name)
                <button type="button" wire:click="goToStep({{ $step }})" @if($currentStep===$step) aria-current="step" @endif class="group rounded-md p-2 text-center focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500">
                    <span class="mx-auto flex h-8 w-8 items-center justify-center rounded-full text-sm font-bold {{ $currentStep===$step ? 'bg-blue-600 text-white' : ($currentStep>$step ? 'bg-green-600 text-white' : 'bg-gray-200 text-gray-600 dark:bg-gray-700 dark:text-gray-300') }}">{{ $currentStep>$step ? '✓' : $step }}</span>
                    <span class="mt-1 block text-xs {{ $currentStep===$step ? 'font-semibold text-blue-700 dark:text-blue-300' : 'text-gray-600 dark:text-gray-400' }}">{{ $name }}</span>
                </button>
            @endforeach
        </div>
    </nav>

    <main class="rounded-lg border border-gray-200 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-900">
        @if($currentStep === 1)
            <h2 class="text-lg font-semibold">1. Información general y territorio</h2>
            <p class="mt-1 text-sm text-gray-500">Datos precargados desde FORM-DVUS-001. Las fechas permanecen editables para reflejar la ejecución final.</p>
            <div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                @foreach(['numero_registro'=>'Número de registro','fecha_registro'=>'Fecha de registro','nombre_proyecto'=>'Nombre del programa o proyecto','facultad_centro'=>'Facultad/Centro','unidad_academica'=>'Unidad académica','departamento_academico'=>'Departamento académico','carrera'=>'Carrera','programa_vinculacion'=>'Programa de vinculación','linea_investigacion'=>'Línea de investigación','modalidad'=>'Modalidad','ejes_prioritarios'=>'Ejes prioritarios','categoria'=>'Categoría'] as $field=>$name)
                    <div class="{{ in_array($field,['nombre_proyecto','linea_investigacion','ejes_prioritarios']) ? 'sm:col-span-2' : '' }}"><label class="{{ $label }}">{{ $name }}</label><input wire:model="general.{{ $field }}" class="{{ $readonly }}" readonly></div>
                @endforeach
                <div><label class="{{ $label }}">Fecha de inicio</label><input type="date" wire:model="general.fecha_inicio" class="{{ $input }}"></div>
                <div><label class="{{ $label }}">Fecha de finalización</label><input type="date" wire:model="general.fecha_finalizacion" class="{{ $input }}"></div>
                <div><label class="{{ $label }}">Duración estimada</label><input value="{{ $informe->duracion_semanas }} semanas" class="{{ $readonly }}" readonly></div>
            </div>
            <h3 class="mt-7 font-semibold">Territorio</h3>
            <div class="mt-3 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                @foreach(['pais'=>'País','region'=>'Región','departamento_territorial'=>'Departamento','municipio'=>'Municipio','aldea_ciudad'=>'Aldea o ciudad','caserio'=>'Caserío'] as $field=>$name)<div><label class="{{ $label }}">{{ $name }}</label><input wire:model="general.{{ $field }}" class="{{ $input }}"></div>@endforeach
            </div>
        @elseif($currentStep === 2)
            <h2 class="text-lg font-semibold">2. Beneficiarios directos</h2>
            <div class="mt-5 grid gap-6 lg:grid-cols-3">
                <section><h3 class="font-semibold">Por sexo</h3><div class="mt-3 space-y-3">@foreach(['hombres'=>'Hombres','mujeres'=>'Mujeres'] as $field=>$name)<div><label class="{{ $label }}">{{ $name }}</label><input type="number" min="0" wire:model.live="beneficiarios.{{ $field }}" class="{{ $input }}"></div>@endforeach</div><p class="mt-3 rounded bg-gray-50 p-2 text-sm dark:bg-gray-800">Total: <strong>{{ $this->totalesBeneficiarios['sexo'] }}</strong></p></section>
                <section><h3 class="font-semibold">Por rango de edad</h3><div class="mt-3 grid grid-cols-2 gap-3">@foreach(['edad_0_10'=>'0–10','edad_11_18'=>'11–18','edad_19_25'=>'19–25','edad_26_35'=>'26–35','edad_36_50'=>'36–50','edad_51_65'=>'51–65','edad_66_80'=>'66–80','edad_81_mas'=>'Mayor de 81'] as $field=>$name)<div><label class="{{ $label }}">{{ $name }}</label><input type="number" min="0" wire:model.live="beneficiarios.{{ $field }}" class="{{ $input }}"></div>@endforeach</div><p class="mt-3 rounded bg-gray-50 p-2 text-sm dark:bg-gray-800">Total: <strong>{{ $this->totalesBeneficiarios['edad'] }}</strong></p></section>
                <section><h3 class="font-semibold">Por etnia y sexo</h3><div class="mt-3 grid grid-cols-2 gap-3">@foreach(['indigena_hombres'=>'Indígena H','indigena_mujeres'=>'Indígena M','afrodescendiente_hombres'=>'Afrodesc. H','afrodescendiente_mujeres'=>'Afrodesc. M','mestizo_hombres'=>'Mestizo H','mestizo_mujeres'=>'Mestizo M'] as $field=>$name)<div><label class="{{ $label }}">{{ $name }}</label><input type="number" min="0" wire:model.live="beneficiarios.{{ $field }}" class="{{ $input }}"></div>@endforeach</div><p class="mt-3 rounded bg-gray-50 p-2 text-sm dark:bg-gray-800">Total: <strong>{{ $this->totalesBeneficiarios['etnia'] }}</strong></p></section>
            </div>
            @if(count(array_unique($this->totalesBeneficiarios)) > 1)<p class="mt-5 rounded-md border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200">Advertencia: las distribuciones por sexo, edad y etnia no representan el mismo total.</p>@endif
        @elseif($currentStep === 3)
            <h2 class="text-lg font-semibold">3. Equipo ejecutor, estudiantes y voluntarios</h2>
            <h3 class="mt-5 font-semibold">Equipo docente</h3>
            <div class="mt-2 overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 dark:bg-gray-800"><tr>@foreach(['Nombre','N.º empleado','Correo','Categoría','Departamento','Horas','Participación'] as $h)<th class="px-3 py-2 text-left">{{ $h }}</th>@endforeach</tr></thead><tbody>@foreach($equipo as $i=>$row)<tr class="border-t dark:border-gray-700"><td class="px-3 py-2">{{ $row['nombre'] }} @if($row['es_coordinador'])<span class="text-xs text-blue-700">Coordinador</span>@endif</td><td class="px-3 py-2">{{ $row['numero_empleado'] }}</td><td class="px-3 py-2">{{ $row['correo'] }}</td><td class="px-3 py-2">{{ $row['categoria'] }}</td><td class="px-3 py-2">{{ $row['departamento'] }}</td><td class="px-3 py-2"><input type="number" min="0" step="0.5" wire:model="equipo.{{ $i }}.horas_dedicadas" class="{{ $input }} min-w-24"></td><td class="px-3 py-2"><input wire:model="equipo.{{ $i }}.tipo_participacion" class="{{ $input }} min-w-32"></td></tr>@endforeach</tbody></table></div>
            <div class="mt-7 flex items-center justify-between"><h3 class="font-semibold">Cooperación internacional</h3><button type="button" wire:click="agregarFila('cooperacion')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar integrante</button></div>
            <div class="mt-2 overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 dark:bg-gray-800"><tr>@foreach(['Nombre','Pasaporte','Correo','País','Universidad','Horas'] as $h)<th class="px-3 py-2 text-left">{{ $h }}</th>@endforeach</tr></thead><tbody>@forelse($cooperacion as $i=>$row)<tr class="border-t dark:border-gray-700">@foreach(['nombre','pasaporte','correo','pais','universidad','horas_dedicadas'] as $field)<td class="px-3 py-2"><input @if($field==='horas_dedicadas') type="number" min="0" @endif wire:model="cooperacion.{{ $i }}.{{ $field }}" class="{{ $input }} min-w-32"></td>@endforeach</tr>@empty<tr><td colspan="6" class="p-3 text-gray-500">No hay cooperación internacional registrada.</td></tr>@endforelse</tbody></table></div>
            <div class="mt-7 flex items-center justify-between"><h3 class="font-semibold">Estudiantes</h3><button type="button" wire:click="agregarFila('estudiantes')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar estudiante</button></div>
            <div class="mt-2 overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 dark:bg-gray-800"><tr>@foreach(['Nombre','Sexo','Cuenta','Carrera','Participación','Cantidad','Horas'] as $h)<th class="px-3 py-2 text-left">{{ $h }}</th>@endforeach</tr></thead><tbody>@foreach($estudiantes as $i=>$row)<tr class="border-t dark:border-gray-700"><td class="px-3 py-2">{{ $row['nombre'] }}</td><td class="px-3 py-2">{{ $row['sexo'] }}</td><td class="px-3 py-2">{{ $row['numero_cuenta'] }}</td><td class="px-3 py-2">{{ $row['carrera'] }}</td><td class="px-3 py-2"><select wire:model="estudiantes.{{ $i }}.tipo_participacion" class="{{ $input }}"><option value="practica_asignatura">Práctica de asignatura</option><option value="pps_servicio_social">PPS o Servicio Social</option><option value="voluntariado">Voluntariado</option></select></td><td class="px-3 py-2"><input type="number" min="1" wire:model="estudiantes.{{ $i }}.cantidad" class="{{ $input }} w-24"></td><td class="px-3 py-2"><input type="number" min="0" wire:model="estudiantes.{{ $i }}.horas_dedicadas" class="{{ $input }} w-24"></td></tr>@endforeach</tbody></table></div>
            <div class="mt-7 flex items-center justify-between"><h3 class="font-semibold">Voluntarios</h3><button type="button" wire:click="agregarFila('voluntarios')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar voluntario</button></div>
            <div class="mt-2 space-y-3">@foreach($voluntarios as $i=>$row)<div class="grid gap-3 rounded-md border p-3 dark:border-gray-700 sm:grid-cols-3 lg:grid-cols-7">@foreach(['nombre'=>'Nombre','sexo'=>'Sexo','identidad'=>'Identidad','departamento'=>'Departamento'] as $field=>$name)<div><label class="{{ $label }}">{{ $name }}</label><input wire:model="voluntarios.{{ $i }}.{{ $field }}" class="{{ $input }}"></div>@endforeach<div><label class="{{ $label }}">Tipo</label><select wire:model="voluntarios.{{ $i }}.tipo" class="{{ $input }}"><option value="profesor_hora">Profesor por hora</option><option value="pas">PAS</option><option value="profesor_permanente">Profesor permanente</option><option value="egresado">Egresado</option></select></div><div><label class="{{ $label }}">Horas</label><input type="number" min="0" wire:model="voluntarios.{{ $i }}.horas_dedicadas" class="{{ $input }}"></div><button type="button" wire:click="quitarFila('voluntarios',{{ $i }})" class="self-end text-sm text-red-600">Quitar</button></div>@endforeach</div>
        @elseif($currentStep === 4)
            <div class="flex items-center justify-between"><h2 class="text-lg font-semibold">4. Contrapartes</h2><button type="button" wire:click="agregarFila('contrapartes')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar contraparte</button></div>
            <div class="mt-5 space-y-5">@foreach($contrapartes as $i=>$row)<article class="rounded-lg border p-4 dark:border-gray-700"><div class="flex justify-between"><h3 class="font-semibold">Contraparte {{ $i+1 }}</h3><button type="button" wire:click="quitarFila('contrapartes',{{ $i }})" class="text-sm text-red-600">Quitar</button></div><div class="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><label class="{{ $label }}">Nombre</label><input wire:model="contrapartes.{{ $i }}.nombre" class="{{ $input }}"></div><div><label class="{{ $label }}">Tipo</label><select wire:model="contrapartes.{{ $i }}.tipo" class="{{ $input }}">@foreach(['gobierno_nacional'=>'Gobierno nacional','gobierno_municipal'=>'Gobierno municipal','ong'=>'ONG','sociedad_civil'=>'Sociedad civil organizada','sector_privado'=>'Sector privado','internacional'=>'Internacional'] as $value=>$name)<option value="{{ $value }}">{{ $name }}</option>@endforeach</select></div>@foreach(['contacto'=>'Contacto','correo'=>'Correo','cargo'=>'Cargo','telefono'=>'Teléfono','territorio'=>'Territorio'] as $field=>$name)<div><label class="{{ $label }}">{{ $name }}</label><input wire:model="contrapartes.{{ $i }}.{{ $field }}" class="{{ $input }}"></div>@endforeach<div><label class="{{ $label }}">Instrumento</label><select wire:model="contrapartes.{{ $i }}.tipo_instrumento" class="{{ $input }}"><option value="">Sin registrar</option><option value="carta_formal">Carta formal</option><option value="carta_intenciones">Carta de intenciones</option><option value="convenio_marco">Convenio marco</option></select></div><div class="sm:col-span-2"><label class="{{ $label }}">Compromisos asumidos</label><textarea wire:model="contrapartes.{{ $i }}.compromisos_asumidos" class="{{ $input }}"></textarea></div><div class="sm:col-span-2"><label class="{{ $label }}">Compromisos cumplidos</label><textarea wire:model="contrapartes.{{ $i }}.compromisos_cumplidos" class="{{ $input }}"></textarea></div><div><label class="{{ $label }}">Aporte monetario</label><input type="number" min="0" step="0.01" wire:model="contrapartes.{{ $i }}.aporte_monetario" class="{{ $input }}"></div><div><label class="{{ $label }}">Aporte en especie valorado</label><input type="number" min="0" step="0.01" wire:model="contrapartes.{{ $i }}.aporte_especie" class="{{ $input }}"></div><div class="sm:col-span-2"><label class="{{ $label }}">Certificación o respaldo</label><input wire:model="contrapartes.{{ $i }}.documento_respaldo" class="{{ $input }}"></div></div></article>@endforeach</div>
        @elseif($currentStep === 5)
            <h2 class="text-lg font-semibold">5. Resultados y ejecución de actividades</h2>
            <div class="mt-4 rounded-md bg-gray-50 p-3 text-sm dark:bg-gray-800"><strong>Objetivo general:</strong> {{ $general['objetivo_general'] ?: 'No registrado' }}</div>
            <div class="mt-5 flex items-center justify-between"><h3 class="font-semibold">Resultados</h3><button type="button" wire:click="agregarFila('resultados')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar resultado</button></div>
            <div class="mt-3 space-y-4">@foreach($resultados as $i=>$row)<article class="rounded-lg border p-4 dark:border-gray-700"><div class="flex justify-between"><strong>Resultado {{ $i+1 }}</strong><button type="button" wire:click="quitarFila('resultados',{{ $i }})" class="text-sm text-red-600">Quitar</button></div><div class="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['objetivo_especifico'=>'Objetivo específico','resultado_planificado'=>'Resultado planificado','indicador_propuesto'=>'Indicador','unidad_medida'=>'Unidad de medida','producto_logrado'=>'Producto logrado','observaciones'=>'Observaciones'] as $field=>$name)<div class="{{ in_array($field,['objetivo_especifico','resultado_planificado','observaciones']) ? 'sm:col-span-2' : '' }}"><label class="{{ $label }}">{{ $name }}</label><textarea rows="2" wire:model="resultados.{{ $i }}.{{ $field }}" class="{{ $input }}"></textarea></div>@endforeach<div><label class="{{ $label }}">Meta numérica</label><input type="number" min="0" step="0.01" wire:model="resultados.{{ $i }}.meta_numerica" class="{{ $input }}"></div><div><label class="{{ $label }}">Valor alcanzado</label><input type="number" min="0" step="0.01" wire:model="resultados.{{ $i }}.valor_alcanzado" class="{{ $input }}"></div><div><label class="{{ $label }}">Cumplimiento %</label><input type="number" min="0" max="100" step="0.01" wire:model="resultados.{{ $i }}.porcentaje_cumplimiento" class="{{ $input }}"></div><div><label class="{{ $label }}">Estado</label><select wire:model="resultados.{{ $i }}.estado" class="{{ $input }}"><option value="alcanzado">Alcanzado</option><option value="parcialmente_alcanzado">Parcialmente alcanzado</option><option value="no_alcanzado">No alcanzado</option><option value="no_aplica">No aplica</option></select></div></div></article>@endforeach</div>
            <div class="mt-7 flex items-center justify-between"><h3 class="font-semibold">Actividades</h3><button type="button" wire:click="agregarFila('actividades')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar actividad</button></div>
            <div class="mt-3 overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 dark:bg-gray-800"><tr>@foreach(['Planificada','Realizada','Responsable','Inicio','Final','Horas','Medio','Estado','Origen',''] as $h)<th class="px-2 py-2 text-left">{{ $h }}</th>@endforeach</tr></thead><tbody>@foreach($actividades as $i=>$row)<tr class="border-t align-top dark:border-gray-700"><td><textarea wire:model="actividades.{{ $i }}.actividad_planificada" class="{{ $input }} min-w-40"></textarea></td><td><textarea wire:model="actividades.{{ $i }}.actividad_realizada" class="{{ $input }} min-w-40"></textarea></td><td><input wire:model="actividades.{{ $i }}.responsable" class="{{ $input }} min-w-32"></td><td><input type="date" wire:model="actividades.{{ $i }}.fecha_inicial" class="{{ $input }}"></td><td><input type="date" wire:model="actividades.{{ $i }}.fecha_final" class="{{ $input }}"></td><td><input type="number" min="0" wire:model="actividades.{{ $i }}.horas_dedicadas" class="{{ $input }} w-24"></td><td><input wire:model="actividades.{{ $i }}.medio_verificacion" class="{{ $input }} min-w-32"></td><td><select wire:model="actividades.{{ $i }}.estado" class="{{ $input }}"><option value="ejecutada">Ejecutada</option><option value="parcial">Parcial</option><option value="no_ejecutada">No ejecutada</option></select></td><td><select wire:model="actividades.{{ $i }}.origen" class="{{ $input }}"><option value="planificada">Planificada</option><option value="emergente">Emergente</option></select></td><td><button type="button" wire:click="quitarFila('actividades',{{ $i }})" class="mt-3 text-red-600">×</button></td></tr>@endforeach</tbody></table></div>
            @foreach(['accionesNoEjecutadas'=>'Acciones no ejecutadas','accionesEmergentes'=>'Acciones emergentes'] as $group=>$title)@php($groupRows = $group === 'accionesNoEjecutadas' ? $accionesNoEjecutadas : $accionesEmergentes)<div class="mt-7 flex items-center justify-between"><h3 class="font-semibold">{{ $title }}</h3><button type="button" wire:click="agregarFila('{{ $group }}')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar</button></div><div class="mt-3 space-y-3">@foreach($groupRows as $i=>$row)<div class="grid gap-3 rounded border p-3 dark:border-gray-700 sm:grid-cols-2 lg:grid-cols-4">@foreach($row as $field=>$value)@if(!in_array($field,['id','informe_final_proyecto_id','created_at','updated_at','informe_final_resultado_id']))<div><label class="{{ $label }}">{{ Str::headline($field) }}</label>@if(in_array($field,['impacto']))<select wire:model="{{ $group }}.{{ $i }}.{{ $field }}" class="{{ $input }}"><option value="bajo">Bajo</option><option value="medio">Medio</option><option value="alto">Alto</option></select>@else<input @if(in_array($field,['fecha'])) type="date" @elseif(in_array($field,['horas'])) type="number" min="0" @endif wire:model="{{ $group }}.{{ $i }}.{{ $field }}" class="{{ $input }}">@endif</div>@endif @endforeach<button type="button" wire:click="quitarFila('{{ $group }}',{{ $i }})" class="self-end text-sm text-red-600">Quitar</button></div>@endforeach</div>@endforeach
        @elseif($currentStep === 6)
            <h2 class="text-lg font-semibold">6. Reflexión, transformación, sostenibilidad y ODS</h2>
            <div class="mt-5 grid gap-4 sm:grid-cols-2">@foreach(['dificultades'=>'Dificultades','acciones_dificultades'=>'Acciones para afrontar dificultades','lecciones_aprendidas'=>'Lecciones aprendidas','buenas_practicas'=>'Buenas prácticas','problema_inicial'=>'Problema inicial identificado','transformacion_lograda'=>'Transformación lograda','mecanismos_sostenibilidad'=>'Mecanismos de sostenibilidad','acciones_contraparte_sostenibilidad'=>'Acciones de la contraparte para sostenibilidad','desafios'=>'Desafíos','respuesta_reforma_universitaria'=>'Respuesta a la reforma universitaria','recomendaciones'=>'Recomendaciones','bibliografia'=>'Bibliografía'] as $field=>$name)<div><label class="{{ $label }}">{{ $name }}</label><textarea rows="4" wire:model="general.{{ $field }}" class="{{ $input }}"></textarea></div>@endforeach</div>
            <div class="mt-7 flex items-center justify-between"><h3 class="font-semibold">Objetivos de Desarrollo Sostenible</h3><button type="button" wire:click="agregarFila('ods')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar ODS</button></div>
            <div class="mt-3 space-y-3">@foreach($ods as $i=>$row)<div class="grid gap-3 rounded border p-3 dark:border-gray-700 sm:grid-cols-2 lg:grid-cols-6"><div><label class="{{ $label }}">ODS</label><select wire:model="ods.{{ $i }}.ods_id" class="{{ $input }}"><option value="">Seleccione</option>@foreach($odsCatalogo as $item)<option value="{{ $item->id }}">{{ $item->nombre }}</option>@endforeach</select></div><div><label class="{{ $label }}">Meta</label><select wire:model="ods.{{ $i }}.meta_contribuye_id" class="{{ $input }}"><option value="">Sin meta catalogada</option>@foreach($metasCatalogo as $meta)<option value="{{ $meta->id }}">{{ $meta->numero_meta }} — {{ Str::limit($meta->descripcion,55) }}</option>@endforeach</select></div><div><label class="{{ $label }}">Aporte</label><input wire:model="ods.{{ $i }}.descripcion_aporte" class="{{ $input }}"></div><div><label class="{{ $label }}">Evidencia</label><input wire:model="ods.{{ $i }}.evidencia" class="{{ $input }}"></div><div><label class="{{ $label }}">Contribución</label><select wire:model="ods.{{ $i }}.nivel_contribucion" class="{{ $input }}"><option value="directa">Directa</option><option value="indirecta">Indirecta</option></select></div><button type="button" wire:click="quitarFila('ods',{{ $i }})" class="self-end text-sm text-red-600">Quitar</button></div>@endforeach</div>
        @elseif($currentStep === 7)
            <h2 class="text-lg font-semibold">7. Valoración comunitaria y ejecución presupuestaria</h2>
            <div class="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><div><label class="{{ $label }}">Total beneficiarios</label><input type="number" min="0" wire:model.live="general.valoracion_total_beneficiarios" class="{{ $input }}"></div><div><label class="{{ $label }}">Tamaño de muestra</label><input type="number" min="0" wire:model.live="general.valoracion_muestra" class="{{ $input }}"></div>@foreach(['excelente'=>'Excelente','muy_buena'=>'Muy buena','regular'=>'Regular','mala'=>'Mala'] as $field=>$name)<div><label class="{{ $label }}">{{ $name }}</label><input type="number" min="0" wire:model.live="general.valoracion_{{ $field }}" class="{{ $input }}"><p class="mt-1 text-xs text-gray-500">{{ $this->porcentajesValoracion[$field] }}%</p></div>@endforeach</div>
            <div class="mt-7 flex items-center justify-between"><h3 class="font-semibold">Detalle presupuestario</h3><button type="button" wire:click="agregarFila('presupuesto')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar concepto</button></div>
            <div class="mt-3 overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 dark:bg-gray-800"><tr>@foreach(['Fuente','Concepto','Unidad','Cantidad','Costo unitario','Costo total','Origen',''] as $h)<th class="px-3 py-2 text-left">{{ $h }}</th>@endforeach</tr></thead><tbody>@foreach($presupuesto as $i=>$row)<tr class="border-t dark:border-gray-700"><td><select wire:model.live="presupuesto.{{ $i }}.fuente" class="{{ $input }}"><option>UNAH</option><option>CONTRAPARTE</option></select></td><td><input wire:model="presupuesto.{{ $i }}.concepto" class="{{ $input }} min-w-36"></td><td><input wire:model="presupuesto.{{ $i }}.unidad" class="{{ $input }} min-w-24"></td><td><input type="number" min="0" step="0.01" wire:model.live="presupuesto.{{ $i }}.cantidad" class="{{ $input }} w-28"></td><td><input type="number" min="0" step="0.01" wire:model.live="presupuesto.{{ $i }}.costo_unitario" class="{{ $input }} w-32"></td><td class="px-3 py-2 font-medium">L {{ number_format((float)($row['cantidad']??0)*(float)($row['costo_unitario']??0),2) }}</td><td><input wire:model="presupuesto.{{ $i }}.origen_fondos" class="{{ $input }} min-w-32"></td><td><button type="button" wire:click="quitarFila('presupuesto',{{ $i }})" class="text-red-600">×</button></td></tr>@endforeach</tbody></table></div>
            <div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><label class="{{ $label }}">Presupuesto planificado</label><input type="number" min="0" step="0.01" wire:model.live="general.presupuesto_planificado" class="{{ $input }}"></div><div><label class="{{ $label }}">Aporte beneficiarios</label><input type="number" min="0" step="0.01" wire:model.live="general.aporte_beneficiarios" class="{{ $input }}"></div><div><label class="{{ $label }}">Otros aportes</label><input type="number" min="0" step="0.01" wire:model.live="general.otros_aportes" class="{{ $input }}"></div></div>
            <div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach(['subtotal'=>'Subtotal base UNAH','infraestructura'=>'Infraestructura 3%','servicios'=>'Servicios públicos 3%','unah'=>'Total institucional','contraparte'=>'Aporte contraparte','ejecucion'=>'Ejecución total','porcentaje'=>'Porcentaje de ejecución'] as $field=>$name)<div class="rounded-md bg-gray-50 p-3 dark:bg-gray-800"><p class="text-xs text-gray-500">{{ $name }}</p><p class="mt-1 font-semibold">{{ $field==='porcentaje' ? number_format($this->totalesPresupuesto[$field],2).'%' : 'L '.number_format($this->totalesPresupuesto[$field],2) }}</p></div>@endforeach</div>
        @else
            <h2 class="text-lg font-semibold">8. Anexos, cierre y validación</h2>
            <div class="mt-5 flex items-center justify-between"><h3 class="font-semibold">Anexos</h3><button type="button" wire:click="agregarFila('anexos')" class="{{ $button }} bg-blue-50 text-blue-700 dark:bg-blue-900/30 dark:text-blue-200">Agregar anexo</button></div>
            <div class="mt-3 space-y-3">@foreach($anexos as $i=>$row)<div class="grid gap-3 rounded border p-3 dark:border-gray-700 sm:grid-cols-2 lg:grid-cols-6"><div><label class="{{ $label }}">Tipo</label><select wire:model="anexos.{{ $i }}.tipo" class="{{ $input }}">@foreach(['materiales'=>'Materiales generados','encuestas'=>'Formularios de encuesta','procesamiento'=>'Informes de procesamiento','fotografias'=>'Fotografías','videos'=>'Videos','difusion'=>'Evidencias de difusión','asistencia'=>'Listas de asistencia','manuales'=>'Manuales','guias'=>'Guías','actas'=>'Actas','otros'=>'Otros'] as $value=>$name)<option value="{{ $value }}">{{ $name }}</option>@endforeach</select></div><div><label class="{{ $label }}">Descripción</label><input wire:model="anexos.{{ $i }}.descripcion" class="{{ $input }}"></div><div><label class="{{ $label }}">Archivo</label><input type="file" wire:model="anexoArchivos.{{ $i }}" class="{{ $input }}">@if($row['archivo']??false)<p class="mt-1 text-xs text-gray-500">Archivo almacenado</p>@endif</div><div><label class="{{ $label }}">Enlace</label><input type="url" wire:model="anexos.{{ $i }}.enlace" class="{{ $input }}"></div><div><label class="{{ $label }}">Fecha</label><input type="date" wire:model="anexos.{{ $i }}.fecha" class="{{ $input }}"></div><button type="button" wire:click="quitarFila('anexos',{{ $i }})" class="self-end text-sm text-red-600">Quitar</button></div>@endforeach</div>
            <h3 class="mt-7 font-semibold">Cierre</h3><div class="mt-3 grid gap-4 sm:grid-cols-2"><div><label class="{{ $label }}">Fecha de cierre</label><input type="date" wire:model="general.fecha_cierre" class="{{ $input }}"></div><div class="sm:col-span-2"><label class="{{ $label }}">Observaciones finales</label><textarea rows="4" wire:model="general.observaciones_finales" class="{{ $input }}"></textarea></div><label class="flex items-start gap-2 sm:col-span-2"><input type="checkbox" wire:model="general.confirmacion_veracidad" class="mt-1 rounded border-gray-300 text-blue-600 focus:ring-blue-500"><span class="text-sm">Confirmo que la información consignada en el INF-001 es veraz.</span></label></div>
            <div class="mt-7 rounded-md border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-100"><strong>Firmas:</strong> la plantilla reserva los espacios para coordinador, jefatura de unidad académica, coordinación de vinculación y decanato/dirección. Completar este formulario no crea firmas, no cambia etapas y no envía notificaciones.</div>
        @endif

        <div class="mt-8 flex flex-col gap-3 border-t pt-5 dark:border-gray-700 sm:flex-row sm:items-center sm:justify-between">
            <div class="flex flex-wrap gap-2"><a href="{{ route('historialproyecto',$proyecto) }}" class="{{ $button }} border border-gray-300 bg-white text-gray-700 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-200">Volver</a>@if($currentStep>1)<button type="button" wire:click="anterior" class="{{ $button }} border border-gray-300 bg-white text-gray-700 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-200">Anterior</button>@endif</div>
            <div class="flex flex-wrap gap-2"><a target="_blank" href="{{ route('informes-finales.inf-001.preview',$informe) }}" class="{{ $button }} border border-blue-300 text-blue-700 dark:border-blue-700 dark:text-blue-300">Vista previa INF-001</a><button type="button" wire:click="guardarBorrador" class="{{ $button }} bg-gray-700 text-white hover:bg-gray-800">Guardar borrador</button>@if($currentStep<8)<button type="button" wire:click="siguiente" class="{{ $button }} bg-blue-600 text-white hover:bg-blue-700">Siguiente</button>@else<button type="button" wire:click="marcarCompleto" wire:confirm="¿Confirma que desea marcar el INF-001 como completo? Esta acción no inicia aprobación ni firmas." class="{{ $button }} bg-green-700 text-white hover:bg-green-800">Marcar completo</button>@endif</div>
        </div>
    </main>
</div>
