<style>
    *{box-sizing:border-box}body{font-family:DejaVu Sans,Arial,sans-serif;font-size:9px;color:#111}.institution{text-align:center}.institution h1{font-size:15px;margin:4px}.institution h2{font-size:12px;margin:4px}.code{color:#07529b;font-weight:bold}h3{margin:18px 0 6px;padding:6px;background:#07529b;color:#fff;font-size:10px;text-transform:uppercase}h4{margin:10px 0 4px;font-size:10px;color:#07529b}table{border-collapse:collapse;width:100%;margin-bottom:8px}th,td{border:1px solid #7b8794;padding:4px;vertical-align:top}th{background:#eaf1f8;text-align:left}.label{font-weight:bold;background:#f4f6f8}.narrative{min-height:42px;white-space:pre-wrap}.page-break{page-break-before:always}.signatures{margin-top:30px}.signature{display:inline-block;width:47%;margin:26px 1% 0;text-align:center;border-top:1px solid #222;padding-top:4px}.muted{color:#5d6773}.right{text-align:right}.center{text-align:center}
</style>
@php
    $b=$informe->beneficiarios;
    $resultadoPromedio=$informe->resultados->count() ? $informe->resultados->avg('porcentaje_cumplimiento') : 0;
    $muestra=max(0,(int)$informe->valoracion_muestra);
    $pct=fn($n)=>$muestra ? round($n/$muestra*100,2) : 0;
@endphp
<div class="institution"><div>UNIVERSIDAD NACIONAL AUTÓNOMA DE HONDURAS</div><div>VINCULACIÓN UNIVERSIDAD–SOCIEDAD</div><h1>INFORME FINAL DE PROGRAMAS Y PROYECTOS DE VINCULACIÓN</h1><h2 class="code">INF-001</h2></div>

<h3>I. Información general</h3>
<table><tr><td class="label">Programa o proyecto</td><td colspan="3">{{ $informe->nombre_proyecto }}</td></tr><tr><td class="label">Registro</td><td>{{ $informe->numero_registro }}</td><td class="label">Fecha de registro</td><td>{{ $informe->fecha_registro?->format('d/m/Y') }}</td></tr><tr><td class="label">Facultad/Centro</td><td>{{ $informe->facultad_centro }}</td><td class="label">Unidad académica</td><td>{{ $informe->unidad_academica }}</td></tr><tr><td class="label">Departamento / Carrera</td><td>{{ $informe->departamento_academico }} / {{ $informe->carrera }}</td><td class="label">Modalidad / Categoría</td><td>{{ $informe->modalidad }} / {{ $informe->categoria }}</td></tr><tr><td class="label">Fechas</td><td>{{ $informe->fecha_inicio?->format('d/m/Y') }} — {{ $informe->fecha_finalizacion?->format('d/m/Y') }}</td><td class="label">Duración</td><td>{{ $informe->duracion_semanas }} semanas</td></tr><tr><td class="label">Territorio</td><td colspan="3">{{ collect([$informe->pais,$informe->region,$informe->departamento_territorial,$informe->municipio,$informe->aldea_ciudad,$informe->caserio])->filter()->implode(', ') }}</td></tr><tr><td class="label">Objetivo general</td><td colspan="3" class="narrative">{{ $informe->objetivo_general }}</td></tr></table>
<h4>Beneficiarios directos</h4><table><tr><th>Hombres</th><th>Mujeres</th><th>Total sexo</th><th>Total edad</th><th>Total etnia</th></tr><tr class="center"><td>{{ $b?->hombres }}</td><td>{{ $b?->mujeres }}</td><td>{{ $b?->total_sexo }}</td><td>{{ $b?->total_edad }}</td><td>{{ $b?->total_etnia }}</td></tr></table>

<h3>II. Equipo ejecutor</h3><table><thead><tr><th>Nombre</th><th>N.º empleado</th><th>Correo</th><th>Categoría</th><th>Departamento</th><th>Horas</th><th>Participación</th></tr></thead><tbody>@forelse($informe->equipoDocente as $row)<tr><td>{{ $row->nombre }}{{ $row->es_coordinador?' (Coordinador)':'' }}</td><td>{{ $row->numero_empleado }}</td><td>{{ $row->correo }}</td><td>{{ $row->categoria }}</td><td>{{ $row->departamento }}</td><td>{{ $row->horas_dedicadas }}</td><td>{{ $row->tipo_participacion }}</td></tr>@empty<tr><td colspan="7">Sin registros.</td></tr>@endforelse</tbody></table>
@if($informe->cooperacion->isNotEmpty())<h4>Cooperación internacional</h4><table><tr><th>Nombre</th><th>Pasaporte</th><th>Correo</th><th>País</th><th>Universidad</th><th>Horas</th></tr>@foreach($informe->cooperacion as $row)<tr><td>{{ $row->nombre }}</td><td>{{ $row->pasaporte }}</td><td>{{ $row->correo }}</td><td>{{ $row->pais }}</td><td>{{ $row->universidad }}</td><td>{{ $row->horas_dedicadas }}</td></tr>@endforeach</table>@endif

<h3>III. Estudiantes</h3><table><tr><th>Nombre</th><th>Sexo</th><th>Cuenta</th><th>Carrera</th><th>Participación</th><th>Cantidad</th><th>Horas</th></tr>@forelse($informe->estudiantes as $row)<tr><td>{{ $row->nombre }}</td><td>{{ $row->sexo }}</td><td>{{ $row->numero_cuenta }}</td><td>{{ $row->carrera }}</td><td>{{ str_replace('_',' ',$row->tipo_participacion) }}</td><td>{{ $row->cantidad }}</td><td>{{ $row->horas_dedicadas }}</td></tr>@empty<tr><td colspan="7">Sin registros.</td></tr>@endforelse</table>

<h3>IV. Voluntarios</h3><table><tr><th>Nombre</th><th>Sexo</th><th>Identidad</th><th>Departamento</th><th>Tipo</th><th>Horas</th></tr>@forelse($informe->voluntarios as $row)<tr><td>{{ $row->nombre }}</td><td>{{ $row->sexo }}</td><td>{{ $row->identidad }}</td><td>{{ $row->departamento }}</td><td>{{ str_replace('_',' ',$row->tipo) }}</td><td>{{ $row->horas_dedicadas }}</td></tr>@empty<tr><td colspan="6">Sin registros.</td></tr>@endforelse</table>

<h3>V. Contraparte</h3><table><tr><th>Nombre / tipo</th><th>Contacto</th><th>Instrumento</th><th>Compromisos asumidos</th><th>Compromisos cumplidos</th><th>Aportes</th></tr>@forelse($informe->contrapartes as $row)<tr><td>{{ $row->nombre }}<br><span class="muted">{{ str_replace('_',' ',$row->tipo) }}</span></td><td>{{ $row->contacto }}<br>{{ $row->correo }}<br>{{ $row->telefono }}</td><td>{{ str_replace('_',' ',$row->tipo_instrumento) }}</td><td>{{ $row->compromisos_asumidos }}</td><td>{{ $row->compromisos_cumplidos }}</td><td>L {{ number_format((float)$row->aporte_monetario+(float)$row->aporte_especie,2) }}</td></tr>@empty<tr><td colspan="6">Sin registros.</td></tr>@endforelse</table>

<div class="page-break"></div><h3>VI. Ejecución</h3><h4>Resultados</h4><table><tr><th>Resultado planificado</th><th>Indicador / meta</th><th>Valor alcanzado</th><th>Cumplimiento</th><th>Estado</th><th>Producto</th></tr>@foreach($informe->resultados as $row)<tr><td>{{ $row->resultado_planificado }}</td><td>{{ $row->indicador_propuesto }} / {{ $row->meta_numerica }} {{ $row->unidad_medida }}</td><td>{{ $row->valor_alcanzado }}</td><td>{{ number_format((float)$row->porcentaje_cumplimiento,2) }}%</td><td>{{ str_replace('_',' ',$row->estado) }}</td><td>{{ $row->producto_logrado }}</td></tr>@endforeach<tr><td colspan="3" class="right label">Promedio de cumplimiento</td><td colspan="3"><strong>{{ number_format($resultadoPromedio,2) }}%</strong></td></tr></table>
<h4>Actividades</h4><table><tr><th>Planificada</th><th>Realizada</th><th>Responsable</th><th>Fechas</th><th>Horas</th><th>Medio / estado</th></tr>@foreach($informe->actividades as $row)<tr><td>{{ $row->actividad_planificada }}</td><td>{{ $row->actividad_realizada }}</td><td>{{ $row->responsable }}</td><td>{{ $row->fecha_inicial?->format('d/m/Y') }} — {{ $row->fecha_final?->format('d/m/Y') }}</td><td>{{ $row->horas_dedicadas }}</td><td>{{ $row->medio_verificacion }} / {{ $row->estado }}</td></tr>@endforeach</table>

<h3>VII. Acciones no ejecutadas</h3><table><tr><th>Resultado</th><th>Actividad</th><th>Explicación</th><th>Afectación</th><th>Responsable</th><th>Impacto</th></tr>@forelse($informe->accionesNoEjecutadas as $row)<tr><td>{{ $row->resultado_previsto }}</td><td>{{ $row->actividad_planificada }}</td><td>{{ $row->explicacion }}</td><td>{{ $row->afectacion_proyecto }}</td><td>{{ $row->responsable }}</td><td>{{ $row->impacto }}</td></tr>@empty<tr><td colspan="6">No se registraron acciones no ejecutadas.</td></tr>@endforelse</table>

<h3>VIII. Acciones emergentes</h3><table><tr><th>Producto</th><th>Actividad</th><th>Justificación</th><th>Responsables</th><th>Fecha</th><th>Horas</th></tr>@forelse($informe->accionesEmergentes as $row)<tr><td>{{ $row->producto_logrado }}</td><td>{{ $row->actividad_realizada }}</td><td>{{ $row->justificacion }}</td><td>{{ $row->responsables }}</td><td>{{ $row->fecha?->format('d/m/Y') }}</td><td>{{ $row->horas }}</td></tr>@empty<tr><td colspan="6">No se registraron acciones emergentes.</td></tr>@endforelse</table>

<h3>IX. Reflexión</h3>@foreach(['dificultades'=>'Dificultades','acciones_dificultades'=>'Acciones frente a dificultades','lecciones_aprendidas'=>'Lecciones aprendidas','buenas_practicas'=>'Buenas prácticas','problema_inicial'=>'Problema inicial','transformacion_lograda'=>'Transformación lograda','mecanismos_sostenibilidad'=>'Sostenibilidad','desafios'=>'Desafíos','respuesta_reforma_universitaria'=>'Reforma universitaria','recomendaciones'=>'Recomendaciones'] as $field=>$label)<h4>{{ $label }}</h4><div class="narrative">{{ $informe->{$field} }}</div>@endforeach
<h4>ODS</h4><table><tr><th>ODS</th><th>Meta</th><th>Aporte</th><th>Evidencia</th><th>Nivel</th></tr>@foreach($informe->ods as $row)<tr><td>{{ $row->ods?->nombre }}</td><td>{{ $row->meta_ods }}</td><td>{{ $row->descripcion_aporte }}</td><td>{{ $row->evidencia }}</td><td>{{ $row->nivel_contribucion }}</td></tr>@endforeach</table>
<h4>Valoración comunitaria</h4><table><tr><th>Beneficiarios</th><th>Muestra</th><th>Excelente</th><th>Muy buena</th><th>Regular</th><th>Mala</th></tr><tr><td>{{ $informe->valoracion_total_beneficiarios }}</td><td>{{ $muestra }}</td><td>{{ $informe->valoracion_excelente }} ({{ $pct($informe->valoracion_excelente) }}%)</td><td>{{ $informe->valoracion_muy_buena }} ({{ $pct($informe->valoracion_muy_buena) }}%)</td><td>{{ $informe->valoracion_regular }} ({{ $pct($informe->valoracion_regular) }}%)</td><td>{{ $informe->valoracion_mala }} ({{ $pct($informe->valoracion_mala) }}%)</td></tr></table>

<div class="page-break"></div><h3>X. Presupuesto</h3><table><tr><th>Fuente</th><th>Concepto</th><th>Unidad</th><th>Cantidad</th><th>Costo unitario</th><th>Costo total</th></tr>@foreach($informe->presupuestoDetalles as $row)<tr><td>{{ $row->fuente }}</td><td>{{ $row->concepto }}</td><td>{{ $row->unidad }}</td><td>{{ $row->cantidad }}</td><td>L {{ number_format((float)$row->costo_unitario,2) }}</td><td>L {{ number_format($row->costo_total,2) }}</td></tr>@endforeach<tr><td colspan="5" class="right label">Subtotal base UNAH</td><td>L {{ number_format($informe->subtotal_unah_base,2) }}</td></tr><tr><td colspan="5" class="right label">Infraestructura 3%</td><td>L {{ number_format($informe->infraestructura_unah,2) }}</td></tr><tr><td colspan="5" class="right label">Servicios públicos 3%</td><td>L {{ number_format($informe->servicios_unah,2) }}</td></tr><tr><td colspan="5" class="right label">Aporte UNAH</td><td>L {{ number_format($informe->total_unah,2) }}</td></tr><tr><td colspan="5" class="right label">Aporte contraparte</td><td>L {{ number_format($informe->total_contraparte,2) }}</td></tr><tr><td colspan="5" class="right label">Ejecución total</td><td><strong>L {{ number_format($informe->ejecucion_total,2) }}</strong></td></tr><tr><td colspan="5" class="right label">Ejecución</td><td><strong>{{ number_format($informe->porcentaje_ejecucion,2) }}%</strong></td></tr></table>

<h3>XI. Firmas</h3><p class="muted">Espacios informativos; este documento no crea ni modifica firmas o etapas del flujo.</p><div class="signatures"><div class="signature">Coordinador del proyecto<br>{{ optional($informe->equipoDocente->firstWhere('es_coordinador',true))->nombre }}</div><div class="signature">Jefe de unidad académica</div><div class="signature">Coordinador del comité o unidad de vinculación</div><div class="signature">Decano o director</div></div>

<h3>XII. Anexos</h3><table><tr><th>N.º</th><th>Tipo</th><th>Descripción</th><th>Fecha</th><th>Referencia</th></tr>@forelse($informe->anexos->sortBy('orden') as $row)<tr><td>{{ $loop->iteration }}</td><td>{{ $row->tipo }}</td><td>{{ $row->descripcion }}</td><td>{{ $row->fecha?->format('d/m/Y') }}</td><td>{{ $row->enlace ?: ($row->archivo ? 'Archivo adjunto' : '') }}</td></tr>@empty<tr><td colspan="5">Sin anexos.</td></tr>@endforelse</table>
<p class="muted">Estado del formulario: {{ $informe->estado }} · Fecha de cierre: {{ $informe->fecha_cierre?->format('d/m/Y') }} · Veracidad confirmada: {{ $informe->confirmacion_veracidad ? 'Sí' : 'No' }}</p>
