<?php

namespace App\Http\Requests\ENF;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreEnfAccionRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'codigo_formulario' => ['nullable', 'string', 'max:80'],
            'tipo_accion_id' => ['nullable', 'exists:vinculacion_tipos_accion,id'],
            'modalidad_id' => ['nullable', 'exists:modalidad,id'],
            'centro_facultad_id' => ['nullable', 'exists:centro_facultad,id'],
            'departamento_academico_id' => ['nullable', 'exists:departamento_academico,id'],
            'carrera_id' => ['nullable', 'exists:carrera,id'],
            'nombre_accion' => ['required', 'string', 'max:250'],
            'numero_edicion' => ['nullable', 'integer', 'min:1'],
            'fecha_solicitud' => ['nullable', 'date'],
            'fecha_inicio' => ['nullable', 'date'],
            'fecha_finalizacion' => ['nullable', 'date', 'after_or_equal:fecha_inicio'],
            'resolucion_vra' => ['nullable', 'string', 'max:120'],
            'resolucion_original' => ['nullable', 'string', 'max:120'],
            'resolucion_actualizacion' => ['nullable', 'string', 'max:120'],
            'horas_teoricas' => ['nullable', 'integer', 'min:0'],
            'horas_practicas' => ['nullable', 'integer', 'min:0'],
            'total_horas' => ['nullable', 'integer', 'min:0'],
            'resumen' => ['nullable', 'string'],
            'descripcion_participantes' => ['nullable', 'string'],
            'definicion_problema' => ['nullable', 'string'],
            'objetivo_general' => ['nullable', 'string'],
            'alineamiento_reforma' => ['nullable', 'string'],
            'metodologia' => ['nullable', 'string'],
            'logistica' => ['nullable', 'string'],
            'bibliografia' => ['nullable', 'string'],
            'genera_ingresos' => ['nullable', 'boolean'],
            'mecanismo_administracion' => ['nullable', 'string'],
            'descripcion_excedente' => ['nullable', 'string'],
            'estado_flujo' => ['nullable', 'string', 'max:40'],
            'revision_ciclo' => ['nullable', 'integer', 'min:0'],
            'responsable_revision_id' => ['nullable', 'exists:empleado,id'],
            'fecha_aprobacion' => ['nullable', 'date'],
            'fecha_registro' => ['nullable', 'date'],
            'numero_libro' => ['nullable', 'string', 'max:80'],
            'numero_tomo' => ['nullable', 'string', 'max:80'],
            'numero_folio' => ['nullable', 'string', 'max:80'],
            'numero_registro' => ['nullable', 'string', 'max:100'],
            'campus_id' => ['nullable', 'exists:campus,id'],
            'departamento_id' => ['nullable', 'exists:departamento,id'],
            'municipio_id' => ['nullable', 'exists:municipio,id'],
            'nombre_lugar' => ['nullable', 'string', 'max:180'],
            'aula_auditorio' => ['nullable', 'string', 'max:180'],
            'edificio' => ['nullable', 'string', 'max:180'],
            'modalidad_ejecucion' => ['nullable', 'string', 'max:60'],
            'plataformas' => ['nullable', 'array'],
            'plataformas.*' => ['integer', 'exists:enf_catalogos,id'],
            'catalogos' => ['nullable', 'array'],
            'catalogos.*' => ['nullable', 'array'],
            'catalogos.*.*' => ['nullable', 'integer', 'exists:enf_catalogos,id'],
            'beneficiarios' => ['nullable', 'array'],
            'beneficiarios.hombres' => ['nullable', 'integer', 'min:0'],
            'beneficiarios.mujeres' => ['nullable', 'integer', 'min:0'],
            'beneficiarios.otros' => ['nullable', 'integer', 'min:0'],
            'beneficiarios.total' => ['nullable', 'integer', 'min:0'],
            'beneficiarios.descripcion' => ['nullable', 'string'],
            'coordinador' => ['nullable', 'array'],
            'coordinador.empleado_id' => ['nullable', 'exists:empleado,id'],
            'coordinador.nombre_completo' => ['nullable', 'string', 'max:220'],
            'coordinador.responsabilidades' => ['nullable', 'string'],
            'sistematizador' => ['nullable', 'array'],
            'sistematizador.empleado_id' => ['nullable', 'exists:empleado,id'],
            'sistematizador.nombre_completo' => ['nullable', 'string', 'max:220'],
            'contraparte' => ['nullable', 'array'],
            'contraparte.nombre' => ['nullable', 'string', 'max:220'],
            'contraparte.representante' => ['nullable', 'string', 'max:180'],
            'contraparte.telefono' => ['nullable', 'string', 'max:80'],
            'contraparte.correo' => ['nullable', 'email', 'max:180'],
            'contraparte.compromisos' => ['nullable', 'string'],
            'contraparte.tipo_contraparte_id' => ['nullable', 'exists:enf_catalogos,id'],
            'contraparte.instrumento_alianza_id' => ['nullable', 'exists:enf_catalogos,id'],
            'objetivos_especificos' => ['nullable', 'array'],
            'objetivos_especificos.*' => ['nullable', 'string'],
            'resultados' => ['nullable', 'array'],
            'resultados.*.tipo' => ['nullable', 'string', 'max:80'],
            'resultados.*.descripcion' => ['nullable', 'string'],
            'resultados.*.indicador' => ['nullable', 'string'],
            'ods_ids' => ['nullable', 'array'],
            'ods_ids.*' => ['integer', 'exists:ods,id'],
            'meta_contribuye_ids' => ['nullable', 'array'],
            'meta_contribuye_ids.*' => ['integer', 'exists:metas_contribuye,id'],
            'eje_unah_ids' => ['nullable', 'array'],
            'eje_unah_ids.*' => ['integer', 'exists:ejes_prioritarios_unah,id'],
            'presupuesto_ingresos' => ['nullable', 'array'],
            'presupuesto_ingresos.*.rubro' => ['nullable', 'string', 'max:180'],
            'presupuesto_ingresos.*.cantidad' => ['nullable', 'numeric', 'min:0'],
            'presupuesto_ingresos.*.costo_unitario' => ['nullable', 'numeric', 'min:0'],
            'presupuesto_egresos' => ['nullable', 'array'],
            'presupuesto_egresos.*.rubro' => ['nullable', 'string', 'max:180'],
            'presupuesto_egresos.*.cantidad' => ['nullable', 'numeric', 'min:0'],
            'presupuesto_egresos.*.costo_unitario' => ['nullable', 'numeric', 'min:0'],
            'cronograma' => ['nullable', 'array'],
            'cronograma.*.actividad' => ['nullable', 'string', 'max:250'],
            'cronograma.*.fecha_inicio' => ['nullable', 'date'],
            'cronograma.*.fecha_finalizacion' => ['nullable', 'date'],
            'cronograma.*.responsable' => ['nullable', 'string', 'max:180'],
            'documentos_requeridos' => ['nullable', 'array'],
            'documentos_requeridos.*' => ['nullable', 'string', 'max:220'],
            'supervisor_documentos' => ['nullable', 'array'],
            'supervisor_documentos.oficio_remision_decano.aplica' => [
                'nullable',
                Rule::requiredIf(fn () => in_array('Oficio de remisión del Decano/Director Centro Regional', $this->input('documentos_requeridos', []), true)),
                'in:Si,No',
            ],
            'supervisor_documentos.documento_perfil_programa.aplica' => [
                'nullable',
                Rule::requiredIf(fn () => in_array('Documento perfil del programa de formación', $this->input('documentos_requeridos', []), true)),
                'in:Si,No',
            ],
            'supervisor_documentos.otros_documentos_respaldo.aplica' => [
                'nullable',
                Rule::requiredIf(fn () => in_array('Otros documentos de respaldo', $this->input('documentos_requeridos', []), true)),
                'in:Si,No',
            ],
            'supervisor_documentos_archivos' => ['nullable', 'array'],
            'supervisor_documentos_archivos.oficio_remision_decano' => [
                Rule::excludeIf(fn () => data_get($this->input('supervisor_documentos', []), 'oficio_remision_decano.aplica') !== 'Si'),
                Rule::requiredIf(fn () => data_get($this->input('supervisor_documentos', []), 'oficio_remision_decano.aplica') === 'Si'),
                'file',
                'mimes:pdf,doc,docx,jpg,jpeg,png',
                'max:10240',
            ],
            'supervisor_documentos_archivos.documento_perfil_programa' => [
                Rule::excludeIf(fn () => data_get($this->input('supervisor_documentos', []), 'documento_perfil_programa.aplica') !== 'Si'),
                Rule::requiredIf(fn () => data_get($this->input('supervisor_documentos', []), 'documento_perfil_programa.aplica') === 'Si'),
                'file',
                'mimes:pdf,doc,docx,jpg,jpeg,png',
                'max:10240',
            ],
            'supervisor_documentos_archivos.otros_documentos_respaldo' => [
                Rule::excludeIf(fn () => data_get($this->input('supervisor_documentos', []), 'otros_documentos_respaldo.aplica') !== 'Si'),
                Rule::requiredIf(fn () => data_get($this->input('supervisor_documentos', []), 'otros_documentos_respaldo.aplica') === 'Si'),
                'file',
                'mimes:pdf,doc,docx,jpg,jpeg,png',
                'max:10240',
            ],
        ];
    }
}
