<?php

namespace App\Http\Requests\ENF;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreEnfAccionRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'codigo_formulario' => ['nullable', 'string', 'max:80'],
            'tipo_accion_id' => ['nullable', 'exists:vinculacion_tipos_accion,id'],
            'modalidad_id' => ['nullable', 'exists:modalidad,id'],
            'centro_facultad_id' => ['nullable', 'exists:centro_facultad,id'],
            'departamento_academico_id' => ['nullable', 'exists:departamento_academico,id'],
            'carrera_id' => ['nullable', 'exists:carrera,id'],
            'unidad_academica_responsable_texto' => ['nullable', 'string', 'max:220'],
            'escuela_departamento_texto' => ['nullable', 'string', 'max:220'],
            'nombre_accion' => ['required', 'string', 'max:250'],
            'numero_edicion' => ['nullable', 'integer', 'min:1'],
            'fecha_solicitud' => ['nullable', 'date'],
            'fecha_inicio' => ['nullable', 'date'],
            'fecha_finalizacion' => ['nullable', 'date', 'after_or_equal:fecha_inicio'],
            'resolucion_vra' => ['nullable', 'string', 'max:120'],
            'resolucion_original' => ['nullable', 'string', 'max:120'],
            'resolucion_actualizacion' => ['nullable', 'string', 'max:120'],
            'horas_teoricas' => ['nullable', 'integer', 'min:0'],
            'horas_practicas' => ['nullable', 'integer', 'min:0'],
            'total_horas' => ['nullable', 'integer', 'min:0'],
            'carga_horaria_creditos' => ['nullable', 'integer', 'min:0'],
            'resumen' => ['nullable', 'string'],
            'impacto_esperado' => ['nullable', 'string'],
            'descripcion_participantes' => ['nullable', 'string'],
            'definicion_problema' => ['nullable', 'string'],
            'objetivo_general' => ['nullable', 'string'],
            'alineamiento_reforma' => ['nullable', 'string'],
            'metodologia' => ['nullable', 'string'],
            'logistica' => ['nullable', 'string'],
            'bibliografia' => ['nullable', 'string'],
            'genera_ingresos' => ['nullable', 'boolean'],
            'mecanismo_administracion' => ['nullable', 'string'],
            'descripcion_excedente' => ['nullable', 'string'],
            'estado_flujo' => ['nullable', 'string', 'max:40'],
            'revision_ciclo' => ['nullable', 'integer', 'min:0'],
            'responsable_revision_id' => ['nullable', 'exists:empleado,id'],
            'fecha_aprobacion' => ['nullable', 'date'],
            'fecha_registro' => ['nullable', 'date'],
            'numero_libro' => ['nullable', 'string', 'max:80'],
            'numero_tomo' => ['nullable', 'string', 'max:80'],
            'numero_folio' => ['nullable', 'string', 'max:80'],
            'numero_registro' => ['nullable', 'string', 'max:100'],
            'campus_id' => ['nullable', 'exists:campus,id'],
            'departamento_id' => ['nullable', 'exists:departamento,id'],
            'municipio_id' => ['nullable', 'exists:municipio,id'],
            'nombre_lugar' => ['nullable', 'string', 'max:180'],
            'aula_auditorio' => ['nullable', 'string', 'max:180'],
            'edificio' => ['nullable', 'string', 'max:180'],
            'centro_lugar' => ['nullable', 'string', 'max:180'],
            'modalidad_ejecucion' => ['nullable', 'string', 'max:60'],
            'descripcion_plataformas' => ['nullable', 'string'],
            'plataformas' => ['nullable', 'array'],
            'plataformas.*' => ['integer', 'exists:enf_catalogos,id'],
            'plataformas_presencial' => ['nullable', 'array'],
            'plataformas_presencial.*' => ['integer', 'exists:enf_catalogos,id'],
            'plataformas_distancia' => ['nullable', 'array'],
            'plataformas_distancia.*' => ['integer', 'exists:enf_catalogos,id'],
            'catalogos' => ['nullable', 'array'],
            'catalogos.*' => ['nullable', 'array'],
            'catalogos.*.*' => ['nullable', 'integer', 'exists:enf_catalogos,id'],
            'certificado' => ['nullable', 'array'],
            'certificado.nombre_certificado' => ['nullable', 'string', 'max:220'],
            'certificado.codigo_certificado' => ['nullable', 'string', 'max:120'],
            'certificado.tipo_certificado_id' => ['nullable', 'exists:enf_catalogos,id'],
            'certificado.figura_acreditacion_id' => ['nullable', 'exists:enf_catalogos,id'],
            'certificado.horas_certificadas' => ['nullable', 'integer', 'min:0'],
            'certificado.requisitos_emision' => ['nullable', 'string'],
            'certificado.vigencia_certificado' => ['nullable', 'string', 'max:120'],
            'certificado.fecha_emision_maxima' => ['nullable', 'date'],
            'certificado.pac_certificado' => ['nullable', 'string', 'max:80'],
            'certificado.hora_inicio' => ['nullable', 'date_format:H:i'],
            'certificado.hora_finalizacion' => ['nullable', 'date_format:H:i'],
            'certificado.dias_imparticion' => ['nullable', 'array'],
            'certificado.dias_imparticion.*' => ['nullable', 'in:Do,Lu,Ma,Mi,Ju,Vi,Sa'],
            'certificado_carreras' => ['nullable', 'array'],
            'certificado_carreras.*.carrera_id' => ['nullable', 'exists:carrera,id'],
            'certificado_carreras.*.centro_facultad_id' => ['nullable', 'exists:centro_facultad,id'],
            'certificado_carreras.*.nombre_carrera' => ['nullable', 'string', 'max:220'],
            'certificado_carreras.*.acuerdo_consejo_universitario' => ['nullable', 'string', 'max:180'],
            'espacios_aprendizaje' => ['nullable', 'array'],
            'espacios_aprendizaje.*.nombre' => ['nullable', 'string', 'max:220'],
            'espacios_aprendizaje.*.codigo' => ['nullable', 'string', 'max:80'],
            'espacios_aprendizaje.*.creditos' => ['nullable', 'integer', 'min:0'],
            'espacios_aprendizaje.*.horas' => ['nullable', 'integer', 'min:0'],
            'espacios_aprendizaje.*.descripcion' => ['nullable', 'string'],
            'beneficiarios' => ['nullable', 'array'],
            'beneficiarios.hombres' => ['nullable', 'integer', 'min:0'],
            'beneficiarios.mujeres' => ['nullable', 'integer', 'min:0'],
            'beneficiarios.otros' => ['nullable', 'integer', 'min:0'],
            'beneficiarios.total' => ['nullable', 'integer', 'min:0'],
            'beneficiarios.descripcion' => ['nullable', 'string'],
            'coordinador' => ['nullable', 'array'],
            'coordinador.empleado_id' => ['nullable', 'exists:empleado,id'],
            'coordinador.nombre_completo' => ['nullable', 'string', 'max:220'],
            'coordinador.numero_empleado' => ['nullable', 'string', 'max:80'],
            'coordinador.identidad' => ['nullable', 'string', 'max:80'],
            'coordinador.correo' => ['nullable', 'email', 'max:180'],
            'coordinador.celular' => ['nullable', 'string', 'max:80'],
            'coordinador.categoria' => ['nullable', 'string', 'max:120'],
            'coordinador.departamento' => ['nullable', 'string', 'max:180'],
            'coordinador.responsabilidades' => ['nullable', 'string'],
            'sistematizador' => ['nullable', 'array'],
            'sistematizador.empleado_id' => ['nullable', 'exists:empleado,id'],
            'sistematizador.nombre_completo' => ['nullable', 'string', 'max:220'],
            'sistematizador.numero_empleado' => ['nullable', 'string', 'max:80'],
            'sistematizador.identidad' => ['nullable', 'string', 'max:80'],
            'sistematizador.correo' => ['nullable', 'email', 'max:180'],
            'sistematizador.celular' => ['nullable', 'string', 'max:80'],
            'sistematizador.categoria' => ['nullable', 'string', 'max:120'],
            'sistematizador.departamento' => ['nullable', 'string', 'max:180'],
            'equipo_docente' => ['nullable', 'array'],
            'equipo_docente.*.nombre_completo' => ['nullable', 'string', 'max:220'],
            'equipo_docente.*.numero_empleado' => ['nullable', 'string', 'max:80'],
            'equipo_docente.*.identidad' => ['nullable', 'string', 'max:80'],
            'equipo_docente.*.espacio_aprendizaje' => ['nullable', 'string', 'max:220'],
            'equipo_docente.*.correo' => ['nullable', 'email', 'max:180'],
            'equipo_docente.*.categoria' => ['nullable', 'string', 'max:120'],
            'equipo_docente.*.departamento' => ['nullable', 'string', 'max:180'],
            'equipo_docente.*.jornada_laboral' => ['nullable', 'string', 'max:120'],
            'equipo_docente.*.ultimo_titulo' => ['nullable', 'string', 'max:180'],
            'equipo_docente.*.pais_procedencia' => ['nullable', 'string', 'max:120'],
            'equipo_docente.*.universidad_procedencia' => ['nullable', 'string', 'max:180'],
            'equipo_docente.*.perfil_docente' => ['nullable', 'string', 'max:80'],
            'equipo_docente.*.carga_academica_pac' => ['nullable', 'in:Si,No'],
            'equipo_docente.*.contratacion_jornada_contraria' => ['nullable', 'in:Si,No'],
            'consultores_nacionales' => ['nullable', 'array'],
            'consultores_nacionales.*.nombre_completo' => ['nullable', 'string', 'max:220'],
            'consultores_nacionales.*.profesion' => ['nullable', 'string', 'max:180'],
            'consultores_nacionales.*.correo' => ['nullable', 'email', 'max:180'],
            'consultores_nacionales.*.horas_contratadas' => ['nullable', 'integer', 'min:0'],
            'consultores_nacionales.*.identidad' => ['nullable', 'string', 'max:80'],
            'consultores_nacionales.*.espacio_aprendizaje' => ['nullable', 'string', 'max:220'],
            'consultores_nacionales.*.ultimo_titulo' => ['nullable', 'string', 'max:180'],
            'consultores_nacionales.*.pais_procedencia' => ['nullable', 'string', 'max:120'],
            'consultores_nacionales.*.universidad_procedencia' => ['nullable', 'string', 'max:180'],
            'consultores_nacionales.*.perfil_docente' => ['nullable', 'string', 'max:80'],
            'consultores_nacionales.*.carga_academica_pac' => ['nullable', 'in:Si,No'],
            'consultores_nacionales.*.contratacion_jornada_contraria' => ['nullable', 'in:Si,No'],
            'consultores_internacionales' => ['nullable', 'array'],
            'consultores_internacionales.*.nombre_completo' => ['nullable', 'string', 'max:220'],
            'consultores_internacionales.*.nacionalidad' => ['nullable', 'string', 'max:120'],
            'consultores_internacionales.*.correo' => ['nullable', 'email', 'max:180'],
            'consultores_internacionales.*.horas_contratadas' => ['nullable', 'integer', 'min:0'],
            'consultores_internacionales.*.identidad' => ['nullable', 'string', 'max:80'],
            'consultores_internacionales.*.espacio_aprendizaje' => ['nullable', 'string', 'max:220'],
            'consultores_internacionales.*.ultimo_titulo' => ['nullable', 'string', 'max:180'],
            'consultores_internacionales.*.pais_procedencia' => ['nullable', 'string', 'max:120'],
            'consultores_internacionales.*.universidad_procedencia' => ['nullable', 'string', 'max:180'],
            'consultores_internacionales.*.perfil_docente' => ['nullable', 'string', 'max:80'],
            'consultores_internacionales.*.carga_academica_pac' => ['nullable', 'in:Si,No'],
            'consultores_internacionales.*.contratacion_jornada_contraria' => ['nullable', 'in:Si,No'],
            'participacion_universitaria' => ['nullable', 'array'],
            'participacion_universitaria.*.tipo_participacion' => ['nullable', 'string', 'max:120'],
            'participacion_universitaria.*.cantidad' => ['nullable', 'integer', 'min:0'],
            'participacion_universitaria.*.hombres' => ['nullable', 'integer', 'min:0'],
            'participacion_universitaria.*.mujeres' => ['nullable', 'integer', 'min:0'],
            'practicas_asignatura' => ['nullable', 'array'],
            'practicas_asignatura.*.asignatura_id' => ['nullable', 'exists:asignaturas,id'],
            'practicas_asignatura.*.periodo_academico_id' => ['nullable', 'exists:periodos_academicos,id'],
            'practicas_asignatura.*.codigo' => ['nullable', 'string', 'max:80'],
            'practicas_asignatura.*.nombre' => ['nullable', 'string', 'max:220'],
            'practicas_asignatura.*.periodo_academico' => ['nullable', 'string', 'max:120'],
            'practicas_asignatura.*.matricula_total' => ['nullable', 'integer', 'min:0'],
            'practicas_asignatura.*.hombres' => ['nullable', 'integer', 'min:0'],
            'practicas_asignatura.*.mujeres' => ['nullable', 'integer', 'min:0'],
            'contraparte' => ['nullable', 'array'],
            'contraparte.tiene_contraparte' => ['nullable', 'in:Si,No'],
            'contraparte.nombre' => [
                'nullable',
                Rule::requiredIf(fn () => data_get($this->input('contraparte', []), 'tiene_contraparte') === 'Si'),
                'string',
                'max:220',
            ],
            'contraparte.representante' => ['nullable', 'string', 'max:180'],
            'contraparte.cargo_contacto' => ['nullable', 'string', 'max:180'],
            'contraparte.telefono' => ['nullable', 'string', 'max:80'],
            'contraparte.correo' => ['nullable', 'email', 'max:180'],
            'contraparte.direccion' => ['nullable', 'string'],
            'contraparte.compromisos' => ['nullable', 'string'],
            'contraparte.tipo_contraparte_id' => ['nullable', 'exists:enf_catalogos,id'],
            'contraparte.instrumento_alianza_id' => ['nullable', 'exists:enf_catalogos,id'],
            'objetivos_especificos' => ['nullable', 'array'],
            'objetivos_especificos.*' => ['nullable', 'string'],
            'resultados' => ['nullable', 'array'],
            'resultados.*.tipo' => ['nullable', 'string', 'max:80'],
            'resultados.*.descripcion' => ['nullable', 'string'],
            'resultados.*.indicador' => ['nullable', 'string'],
            'ods_ids' => ['nullable', 'array'],
            'ods_ids.*' => ['integer', 'exists:ods,id'],
            'meta_contribuye_ids' => ['nullable', 'array'],
            'meta_contribuye_ids.*' => ['integer', 'exists:metas_contribuye,id'],
            'eje_unah_ids' => ['nullable', 'array'],
            'eje_unah_ids.*' => ['integer', 'exists:ejes_prioritarios_unah,id'],
            'presupuesto_ingresos' => ['nullable', 'array'],
            'presupuesto_ingresos.*.rubro' => ['nullable', 'string', 'max:180'],
            'presupuesto_ingresos.*.cantidad' => ['nullable', 'numeric', 'min:0'],
            'presupuesto_ingresos.*.costo_unitario' => ['nullable', 'numeric', 'min:0'],
            'presupuesto_egresos' => ['nullable', 'array'],
            'presupuesto_egresos.*.rubro' => ['nullable', 'string', 'max:180'],
            'presupuesto_egresos.*.cantidad' => ['nullable', 'numeric', 'min:0'],
            'presupuesto_egresos.*.costo_unitario' => ['nullable', 'numeric', 'min:0'],
            'aporte_unah' => ['nullable', 'array'],
            'aporte_unah.*.rubro' => ['nullable', 'string', 'max:180'],
            'aporte_unah.*.cantidad' => ['nullable', 'numeric', 'min:0'],
            'aporte_unah.*.costo_unitario' => ['nullable', 'numeric', 'min:0'],
            'cronograma' => ['nullable', 'array'],
            'cronograma.*.actividad' => ['nullable', 'string', 'max:250'],
            'cronograma.*.producto' => ['nullable', 'string', 'max:250'],
            'cronograma.*.fecha_inicio' => ['nullable', 'date'],
            'cronograma.*.fecha_finalizacion' => ['nullable', 'date'],
            'cronograma.*.responsable' => ['nullable', 'string', 'max:180'],
            'cronograma.*.horas_requeridas' => ['nullable', 'integer', 'min:0'],
            'documentos_requeridos' => ['nullable', 'array'],
            'documentos_requeridos.*' => ['nullable', 'string', 'max:220'],
            'documentos_archivos' => ['nullable', 'array'],
            'documentos_archivos.descripcion_plan_estudios' => [
                'nullable',
                'file',
                'mimes:pdf,doc,docx,jpg,jpeg,png',
                'max:10240',
            ],
            'firmas' => ['nullable', 'array'],
            'firmas.*.rol_firma' => ['nullable', 'string', 'max:150'],
            'firmas.*.nombre_firmante' => ['nullable', 'string', 'max:220'],
            'firmas.*.observaciones' => ['nullable', 'string'],
            'supervisor_documentos' => ['nullable', 'array'],
            'supervisor_documentos.oficio_remision_decano.aplica' => [
                Rule::requiredIf(fn () => $this->input('codigo_formulario') === 'FORM-DVUS-018'),
                'in:Si,No',
            ],
            'supervisor_documentos.documento_perfil_programa.aplica' => [
                Rule::requiredIf(fn () => $this->input('codigo_formulario') === 'FORM-DVUS-018'),
                'in:Si,No',
            ],
            'supervisor_documentos.otros_documentos_respaldo.aplica' => [
                Rule::requiredIf(fn () => $this->input('codigo_formulario') === 'FORM-DVUS-018'),
                'in:Si,No',
            ],
            'supervisor_documentos_archivos' => ['nullable', 'array'],
            'supervisor_documentos_archivos.oficio_remision_decano' => [
                Rule::excludeIf(fn () => data_get($this->input('supervisor_documentos', []), 'oficio_remision_decano.aplica') !== 'Si'),
                Rule::requiredIf(fn () => data_get($this->input('supervisor_documentos', []), 'oficio_remision_decano.aplica') === 'Si'),
                'file',
                'mimes:pdf,doc,docx,jpg,jpeg,png',
                'max:10240',
            ],
            'supervisor_documentos_archivos.documento_perfil_programa' => [
                Rule::excludeIf(fn () => data_get($this->input('supervisor_documentos', []), 'documento_perfil_programa.aplica') !== 'Si'),
                Rule::requiredIf(fn () => data_get($this->input('supervisor_documentos', []), 'documento_perfil_programa.aplica') === 'Si'),
                'file',
                'mimes:pdf,doc,docx,jpg,jpeg,png',
                'max:10240',
            ],
            'supervisor_documentos_archivos.otros_documentos_respaldo' => [
                Rule::excludeIf(fn () => data_get($this->input('supervisor_documentos', []), 'otros_documentos_respaldo.aplica') !== 'Si'),
                Rule::requiredIf(fn () => data_get($this->input('supervisor_documentos', []), 'otros_documentos_respaldo.aplica') === 'Si'),
                'file',
                'mimes:pdf,doc,docx,jpg,jpeg,png',
                'max:10240',
            ],
        ];
    }

    public function attributes(): array
    {
        return [
            'nombre_accion' => 'nombre del certificado',
            'fecha_solicitud' => 'fecha de solicitud',
            'fecha_inicio' => 'fecha de inicio',
            'fecha_finalizacion' => 'fecha de finalización',
            'certificado.codigo_certificado' => 'código de certificado',
            'certificado.tipo_certificado_id' => 'tipo de certificado',
            'certificado.fecha_emision_maxima' => 'fecha máxima de emisión',
            'certificado.hora_inicio' => 'hora de inicio',
            'certificado.hora_finalizacion' => 'hora de finalización',
            'certificado.dias_imparticion' => 'días de impartición',
            'certificado_carreras.*.nombre_carrera' => 'nombre de carrera',
            'certificado_carreras.*.acuerdo_consejo_universitario' => 'acuerdo de Consejo Universitario',
            'espacios_aprendizaje.*.nombre' => 'nombre de asignatura',
            'espacios_aprendizaje.*.codigo' => 'código de asignatura',
            'espacios_aprendizaje.*.creditos' => 'créditos',
            'espacios_aprendizaje.*.horas' => 'horas',
            'beneficiarios.hombres' => 'cupos para hombres',
            'beneficiarios.mujeres' => 'cupos para mujeres',
            'beneficiarios.total' => 'total de cupos',
            'coordinador.nombre_completo' => 'nombre del coordinador',
            'coordinador.correo' => 'correo del coordinador',
            'equipo_docente.*.nombre_completo' => 'nombre del docente',
            'equipo_docente.*.correo' => 'correo del docente',
            'contraparte.nombre' => 'nombre de la contraparte',
            'contraparte.correo' => 'correo de la contraparte',
            'documentos_archivos.descripcion_plan_estudios' => 'descripciones mínimas del plan de estudios',
            'firmas.*.nombre_firmante' => 'nombre del firmante',
        ];
    }
}
